[Reviewing] Added translations for Reporting_Bad_Behaviour/ and ../Handling_Cheating
osu-translate-zh/osu-wiki pull request #10
Opened 2017-08-23 15:40 UTC by axmmisaka

### Description

Added `.gitignore`, `Reporting_Bad_Behaviour/Handling_Cheating/zh.md` and `Reporting_Bad_Behaviour/zh.md`.
I think there was a translation previously(in old wiki), however it disappeared.
Added .gitignore for gVim.
### Status

Finished. Awaiting for review.
### Changelog

### TODOs
See comments in translated files.
Major problems:
- []Translation of `one-strike policy`
- []Translation of `input-spiltter`
- []Translation of `screamer`

2017-08-23 16:01 UTC, kj415j45 requested changes
用词要官方点(

现在的语气太亲民了(

2017-08-23 16:14 UTC, axmmisaka commented
Officialized some expression.

2017-08-24 14:36 UTC, User670 requested changes

2017-08-24 14:36 UTC, user670 commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，录屏打图可以帮你证明清白。
**不是录屏打图！！！**是用相机录。

2017-08-24 14:36 UTC, user670 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +![使用!report命令的栗子](./img/Report-command.png "使用!report命令的栗子")
别“栗子”了，还是正常说“例子”吧。

2017-08-24 14:36 UTC, user670 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +只应使用这种方式举报开挂玩家。
此方式只应用于举报作弊玩家。

2017-08-24 14:36 UTC, user670 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +你可以以一些玩家在搞事情举报一个频道，也可以举报一批玩家。
一些玩家在搞事情“**时**”举报……

2017-08-24 15:30 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，录屏打图可以帮你证明清白。
This means it in BF4 community - although may not in Chinese. Will change.

2017-08-24 15:51 UTC, axmmisaka commented
Completed requested change.

2017-08-25 16:19 UTC, EeyoreRT requested changes

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +和!report命令不同，用这种方法举报用户只需要一种原因和一些（解释原因的）自定义文本。
用这种方法举报用户只需要**选择一类原因并填写具体解释该原因的自定义内容**
【原文：a type of reason and the custom text        
结合图上点击举报后出现的是 （select reason：（additional info： 两栏，因而建议改成这样翻比较通顺符合。

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +``!report This User Name 在#osu频道发辣鸡``就会变成``!report This_User_Name 在#osu频道发辣鸡``
`辣鸡`用词太随意了…spamming可否翻译成 **无意义刷屏** 呢？ 这样也含概了垃圾信息和刷屏的两种情况。：
 【**!report XXX(user name) 正在#osu频道里无意义刷屏** 就会变成 **!report X_X_X 在osu里无意义刷屏。**】
（不过我想这里的this user name像你这样保留原文也是可以的。也可以选择用XXX， （以及下一行小写）xxx代替

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +记得在举报注释中添加细节。
单单翻成`细节`语意不清。然后`添加`不妨换成**写**， 毕竟是要report的人去写的。
**记得在举报注释中写上更多细节信息。**

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +![这会打开一个举报用户的对话框](img/Report-user-profile.png "这会打开一个举报用户的对话框")
图上只有 report user，没有点击以后的图片，造成困惑。建议：**点击这个**将会打开一个……

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 发布不合适的内容，例如H图（可疑的和暗示性的也考虑在内）
也不仅仅是色情性质的图噢，过火的文字也有可能，尤其在公共聊天的时候，所以单单说图也不合适。补充说明一下吗？
（`pornographic materials`

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +请注意此规定适用于直播链接刷屏。
（Take note that spamming streaming links are applied to this rule.）
这样翻译读起来会造成单一指向的误解。
建议意译一点：请注意此规定**同样适用于用直播链接刷屏的情况** 
或者：请注意**用直播链接刷屏的行为也在此条规定范围内。**

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 我不小心举报了一个玩家！我会被制裁吗？
制裁 这个词过于严重。一般用于犯罪。换成**惩罚**吧

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +你可以以一些玩家在搞事情为由举报一个频道，也可以举报一批玩家。
我认为 搞事情 太过口语化了，**惹事端**或者**引起事端**可以吗？【causing problems

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +-	你的用户页上被禁言了10次
请参考一下w：你的用户主页上**显示被禁言的违规记录已达到10次。**
【issued in your userpage，语句有点不通噢

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +## 我因为作弊被封禁了。 我没有作弊！
**但**我没有作弊！（原文虽然没有but，但这样语句通顺些ww

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +你可能很难接受，但你得相信工作人员。尽管ppy也不想破坏友情，但是他知道几乎没人能被相信。即使是那些你永远不会怀疑的那些和你很亲近的人也可能在你和其他人看不见的地方搞小动作。
这段有错意和重复的问题，建议稍微修改一下w ：【 你可能很难**冷静地**接受**这一事实**，但请相信工作人员。ppy**并不是**想破坏**你们的**友情，但他知道**人心隔肚皮**。即使是那些你永远不会怀疑的很亲近的人也可能**会**在你和其他人看不见的地方搞小动作。 】
【这句ppy knows nearly no one can be trusted，如果翻出 ‘信任’ ‘相信’这样的词，就会与前面的 `相信工作人员` 有冲突，看上去会自相矛盾。（虽然原文并不是指一个意思。）于是我想了想，换成了人心隔肚皮。这样也可以表达出人的心思难以猜测的意思。

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +简单地看看这里的规则： [Osu!:Rules](Osu!:Rules "wikilink")
You can **simply** read the rules here.  不是指“简单地看看规则”噢，这里simply是指操作很简单，直接点进这里具体看。官方肯定希望大家认真具体看规则的XD

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +我们十分感谢你对违规行为的举报。为了相对更快的回复，你也可以给我们直接往 osu@ppy.sh 发邮件。
你也可以直接发邮件给  osu@ppy.sh 阐明情况，这样可以更快地获得回复。

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +不好意思，但如果你被封禁了，工作人员百分百确定你在作弊。一个视频不会起什么作用。
需要加一个连接词更通顺。：……但如果你被封禁了，**意味着**工作人员百分之百确定你在作弊。……

2017-08-25 16:19 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +此系统不仅仅只在游戏内聊天有用，其他地方，例如论坛和这个百科一样存在它。
**它也一样适用于论坛和这个百科中。**

2017-08-25 16:53 UTC, kj415j45 requested changes

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +如规则所说，任何形式的对客户端的篡改；改分；使用宏连打出的combo和自瞄都被认为是作弊。
注意空格。。。

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +<!---one strike-policy的翻译更新,请检查--->
下一次不要用html注释，改用review comment

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +简单地看看这里的规则： [Osu!:Rules](Osu!:Rules "wikilink")
`看看 [osu!规则](/wiki/rules) 。`

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +## 什么是举报系统？
一二行间加一行。
隔开两个标题。

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +举报系统是一个用来通知moderator们不正当行为用户并供他/她们采取行动的重要功能。
参考名词对照表

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +用法：`!report 用户名[原因]`
!report <用户名> [原因]

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +``!report This User Name 在#osu频道发辣鸡``就会变成``!report This_User_Name 在#osu频道发辣鸡``
就会变成 → 应该写作

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +![记得在这来添加原因！](img/Report-user-2.png "记得在这来添加原因！")
记得在这里添加理由

2017-08-25 16:53 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 在聊天里发垃圾信息或刷屏
标题间用空行隔开。。

2017-09-11 15:39 UTC, closed without merging

2017-09-11 18:02 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 我不小心举报了一个玩家！我会被制裁吗？
我会用惩罚 感谢

2017-09-11 18:02 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 我不小心举报了一个玩家！我会被制裁吗？
我会用惩罚 感谢

2017-09-11 18:04 UTC, kj415j45 commented
等分支整理干净后会恢复组织内的分支

2017-09-11 18:05 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 发布不合适的内容，例如H图（可疑的和暗示性的也考虑在内）
嗯，以前考虑过“色情材料”或“色情信息”，不过因为在“例如”里我就例如了一个。

2017-09-11 18:07 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Cheating/zh.md
> +你可能很难接受，但你得相信工作人员。尽管ppy也不想破坏友情，但是他知道几乎没人能被相信。即使是那些你永远不会怀疑的那些和你很亲近的人也可能在你和其他人看不见的地方搞小动作。
翻译很漂亮 学习了

2017-09-11 18:09 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/zh.md
> +举报系统是一个用来通知moderator们不正当行为用户并供他/她们采取行动的重要功能。
好 我刚开始的时候还没有这种神奇的东西