[WIP] Added Tournament_Management_Commands/zh.md
osu-translate-zh/osu-wiki pull request #11
Opened 2017-08-23 18:52 UTC by lslqtz

稍微的写了点东西。
我好像没权限创建分支？虽然我也提交到master就是了。

2017-08-23 18:52 UTC, lslqtz commented on wiki/Tournament_Management_Commands/zh.md
> +  - Referees must join the room lobby in-game, 或使用 IRC 输入 `/join #mp_<room_id>` 进入房间的聊天频道。
需要帮助翻译

2017-08-24 18:25 UTC, kj415j45 requested changes

2017-08-24 18:25 UTC, kj415j45 commented on wiki/Tournament_Management_Commands/zh.md
> +  - 请注意，这并_不能_邀请在 osu! 内开启了`只接收好友发来的私聊消息`的玩家，所以比赛工作人员需要通知玩家关闭该选项。
`_不能_` 两头空格，md解析问题。

2017-08-25 18:47 UTC, kj415j45 approved these changes

2017-08-26 04:03 UTC, Deardrops reviewed
看得出来苟群主很用心，因为我找不出来一个标点符号错误。

2017-08-26 04:03 UTC, Deardrops commented on wiki/Tournament_Management_Commands/zh.md
> +多人游戏房间的创建者也可以使用这些指令。如果创建者离开了，新房主将不能使用这些指令。而如果创建者重新加入房间，他将可以再次使用指令。
最后一个`他`指代不明。
`如果创建者重新加入房间，创建者可以再次使用命令。`

2017-08-26 04:03 UTC, Deardrops commented on wiki/Tournament_Management_Commands/zh.md
> +用户名包含空格的必须被替换为下划线，用户 ID 可能可以替换为用户名。
`可能可以` -> `可以`

2017-08-26 04:03 UTC, Deardrops commented on wiki/Tournament_Management_Commands/zh.md
> +这些指令可以在 osu! 或 IRC 客户端内使用，像是 mIRC，HexChat 或 HydraIRC。
建议：`像是` -> `例如`

2017-08-26 04:03 UTC, Deardrops commented on wiki/Tournament_Management_Commands/zh.md
> +- `!mp lock` - 锁定房间，禁止玩家改变队伍或格子。
建议：`格子` -> `位置`
下面的`格子`一并修改

2017-08-26 04:03 UTC, Deardrops commented on wiki/Tournament_Management_Commands/zh.md
> +- `!mp unlock` - 撤销 `!mp lock` 所产生的影响。
建议： `撤销 !mp lock 的效果`

2017-08-26 10:01 UTC, EeyoreRT requested changes
发现原文的最后有一段没有翻译，是我看漏了吗？
We expect you to act professionally and responsibly in the management of your tournament. Any abuse of these commands to disrupt the play of other users will be dealt with harshly as a violation of our community rules.

2017-08-26 10:01 UTC, EeyoreRT commented on wiki/Tournament_Management_Commands/zh.md
> +您可以用下面的聊天指令管理房间：
建议**比赛房间**，考虑到这个指令是只有这种情况才可以用的，再看原文语气也是这样。所以尽管有大标题了，还是再次强调以不会引发乍读的误解。【原文句式....commands are provided for ...tournament rooms 
您可以用下面的聊天指令管理**比赛**房间。

2017-08-26 10:01 UTC, EeyoreRT commented on wiki/Tournament_Management_Commands/zh.md
> +- `!mp lock` - 锁定房间，禁止玩家改变队伍或格子。
我记得那边的osu！tourney用的是`格子`，是不是还是统一比较好？或者这里干脆详尽一点：改变队伍或格子位置

2017-08-26 10:01 UTC, EeyoreRT commented on wiki/Tournament_Management_Commands/zh.md
> +用户名包含空格的必须被替换为下划线，用户 ID 可能可以替换为用户名。
这句不要翻译 [userid] 和[username]，是说在所有commands里这两种写法都能互换，翻译出中文的`用户名`反而会不明白的。
【[userid] may substitute [username] in all of the commands.】(似乎尖括号会卡comment所以我这里用[ ]代替了）

2017-08-26 10:01 UTC, EeyoreRT commented on wiki/Tournament_Management_Commands/zh.md
> +- `!mp removeref <username> [<username>] …` - 删除房间内的裁判，只有房间的创建者才可以删除裁判。
`删除`--**移除**

2017-08-26 10:38 UTC, benpigchu commented on wiki/Tournament_Management_Commands/zh.md
> +用户名包含空格的必须被替换为下划线，用户 ID 可能可以替换为用户名。
【 “用户名” -> “用户昵称” 】

2017-08-26 17:41 UTC, lslqtz commented on wiki/Tournament_Management_Commands/zh.md
> +您可以用下面的聊天指令管理房间：
是我看漏了

2017-08-26 17:43 UTC, lslqtz commented on wiki/Tournament_Management_Commands/zh.md
> +- `!mp lock` - 锁定房间，禁止玩家改变队伍或格子。
osu!tourney那边已经用了格子，所以建议暂时不修改这个

2017-08-26 17:49 UTC, lslqtz commented
👌

2017-08-26 20:19 UTC, kj415j45 approved these changes

2017-08-26 20:21 UTC, merged