[WIP] Added Do_you_really_want_to_ask_peppy/zh.md
osu-translate-zh/osu-wiki pull request #13
Opened 2017-08-23 19:24 UTC by lslqtz

改了点小东西

2017-08-23 19:25 UTC, lslqtz commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +你好，我理解你想和我亲自联系。但我希望你首先明白，这不是你向我寻求帮助或支持的地方。我将 osu! 支持和个人的聊天消息分开，and also find that answering forum PMs is quite hard to keep up with。
需要帮助翻译

2017-08-23 19:25 UTC, lslqtz commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +对于Accounts问题，支付问题，锦标赛查询以及和 osu! 相关的问题，请发送邮件至 [accounts@ppy.sh](mailto:accounts@ppy.sh) (Accounts问题) 或 [osu@ppy.sh](mailto:osu@ppy.sh) (其它问题)，如果我们的任何支持人员在线，你还可以通过点击页面右下角的 "?" 按钮。
需要帮助翻译

2017-08-23 19:25 UTC, lslqtz commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +如果你希望亲自联系 peppy，并且不是因为 osu! 相关原因的，你可以发送邮件至 [pe@ppy.sh](mailto:pe@ppy.sh)。请注意，发送到该邮箱的相关Accounts或支持都将会被标记为垃圾邮件。
需要帮助翻译

2017-08-23 21:22 UTC, axmmisaka commented
Try reference [this](https://github.com/axmmisaka/osu-wiki/blob/7187e3a457a6acb388f5812f2e9f6fb1f36b215d/wiki/Do_you_really_want_to_ask_peppy/zh.md)

2017-08-23 22:34 UTC, lslqtz commented
very good
我想知道用皮老板能作为正式称呼嘛？

2017-08-23 22:40 UTC, lslqtz commented
已改。
我认为被ban也算账号原因的一种，然后认为皮老板作为称呼不太合适

2017-08-23 22:44 UTC, axmmisaka commented
My translation have a bunch of problem and push request for it is rejected.
Wilco, the translation of ppy will be changed.

2017-08-25 18:35 UTC, kj415j45 approved these changes
ojbk

2017-08-26 00:45 UTC, Deardrops commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +如果你希望亲自联系 peppy，并且非 osu! 相关原因的，你可以发送邮件至 [pe@ppy.sh](mailto:pe@ppy.sh)。请注意，发送到该邮箱的相关账号或支持邮件都将会被标记为垃圾邮件。
`如果由于其他方面的原因，你希望亲自联系 peppy，可以发送邮件至 [pe@ppy.sh](mailto:pe@ppy.sh)。请注意，发送到该邮箱的其他邮件（账号问题或其他问题）都将会被标记为垃圾邮件。`

2017-08-26 00:45 UTC, Deardrops commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +哈喽！我知道你很迫切地想要亲自和我联系。但我希望你明白这不是你找我寻求帮助和支持的地方，我一直将 osu! 支持和个人的聊天消息分开，并且我无法一直坚持回答论坛私信。
`但我希望你明白这不是你找我寻求帮助和支持的地方` ->
`但是亲自联系我并不是你寻求帮助和支持的恰当方式`
联系上下文，这么翻译符合下文的意思。

2017-08-26 06:12 UTC, EeyoreRT requested changes

2017-08-26 06:12 UTC, EeyoreRT commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +哈喽！我知道你很迫切地想要亲自和我联系。但我希望你明白这不是你找我寻求帮助和支持的地方，我一直将 osu! 支持和个人的聊天消息分开，并且我无法一直坚持回答论坛私信。
**我理解你迫切想要和我本人联系的心情。**【I understand your urge to want to contact me personally.
我一直保持着将osu！支持 和个人聊天信息分开来的习惯，并且**一个个地去回复论坛私信工作量实在太大。**【 answering forum pms is quite hard to keep up with. 【这句一定要换种翻译说法。说“无法坚持”会给读的人留下不必要的不好印象。

2017-08-26 06:12 UTC, EeyoreRT commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +你可以在[技术支持论坛(英文)](https://osu.ppy.sh/forum/5)中搜索或提出一个新的问题，论坛里有很多人可以帮助你解决问题，因此这比找我更快。
论坛里有很多人可以帮助你解决问题，**这会比联系我要快得多**

2017-08-26 06:12 UTC, EeyoreRT commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +对于账号问题，支付问题，比赛查询以及和 osu! 相关的问题，请发送邮件至 [accounts@ppy.sh](mailto:accounts@ppy.sh) (账号问题) 或 [osu@ppy.sh](mailto:osu@ppy.sh) (其它问题)，如果我们的任何支持人员在线，你还可以通过点击页面右下角的 "?" 按钮。
-似乎漏翻了ban follow-ups噢？: ……支付问题，**有关封禁的后续询问**，比赛查询以及和……
-最后一句话好像没讲完，句尾加上补足 ：通过点击页面右下角的“？” 按钮**联系他们**。

2017-08-26 06:12 UTC, EeyoreRT commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +如果你希望亲自联系 peppy，并且非 osu! 相关原因的，你可以发送邮件至 [pe@ppy.sh](mailto:pe@ppy.sh)。请注意，发送到该邮箱的相关账号或支持邮件都将会被标记为垃圾邮件。
附议上面提议的，很通顺ww只是三个 `其他` 读起来有点意义有点冲突。第一个“其他”要保留，算作总结除了以上情况的“其他”。那么括号里的改成（请求游戏帮助或账号相关问题）可以吗？暂时没有想到更合适的，请作参考一下w【any support of account-related requests

2017-08-26 17:57 UTC, lslqtz commented
大概ojbk了 👌

2017-08-26 20:22 UTC, kj415j45 commented on wiki/Do_you_really_want_to_ask_peppy/zh.md
> +对于账号问题，支付问题，比赛查询以及和 osu! 相关的问题，请发送邮件至 [accounts@ppy.sh](mailto:accounts@ppy.sh) (账号问题) 或 [osu@ppy.sh](mailto:osu@ppy.sh) (其它问题)，如果我们的任何支持人员在线，你还可以通过点击页面右下角的 "?" 按钮。
@lslqtz 改一下这里？

2017-08-26 20:35 UTC, kj415j45 approved these changes

2017-08-26 20:37 UTC, merged