[ZH] Welcome
osu-translate-zh/osu-wiki pull request #17
Opened 2017-09-01 16:48 UTC by kj415j45

### 介绍

重写中文欢迎页

ref: ppy/osu-wiki#94 osu-translate-zh/osu-wiki#16 osu-translate-zh/osu-wiki#15

### 基本要求

- [x] 简短而清晰地介绍 osu! 是什么(不得超过 125 字)
- [ ] 链接到新玩家最可能感兴趣的页面
- [ ] 简短介绍谱面及摸图(modding)，然后使用链接指向相关细节
- [ ] 介绍 osu! 的主要活动(世界杯)
- [ ] 简短介绍如何向 wiki 贡献，然后链接到 owcg
- [x] 不要看起来像坨屎

2017-09-01 16:59 UTC, huoyaoyuan requested changes

2017-09-01 16:59 UTC, huoyaoyuan commented on wiki/Welcome/zh.md
> +osu! 是一款有着四个模式的免费音乐游戏。它在全世界有上千万的玩家，并拥有上万张谱面。你可以离线或者在线游玩，并与世界各地玩家同台竞技。同时，所有人都可以为他喜欢的歌制作并上传自己的[谱面](/wiki/beatmaps)，然后与全球玩家一同分享！
为**自己**喜欢的**音乐**

2017-09-23 13:24 UTC, Gennadiyev commented on wiki/Welcome/zh.md
> +osu! 是一款有着四个模式的免费音乐游戏。它在全世界有上千万的玩家，并拥有上万张谱面。你可以离线或者在线游玩，并与世界各地玩家同台竞技。同时，所有人都可以为他喜欢的歌制作并上传自己的[谱面](/wiki/beatmaps)，然后与全球玩家一同分享！
它在全世界有上千万的玩家 ->全球玩家数已突破千万

同时，所有人都可以为他喜欢的歌制作并上传自己的[谱面](/wiki/beatmaps)，然后与全球玩家一同分享！
->
同时，玩家可以自由选曲，创作属于自己的[谱面](/wiki/beatmaps)并上传，与全球玩家一同分享！

2017-09-24 11:38 UTC, lslqtz commented on wiki/Welcome/zh.md
> +osu! 是一款有着四个模式的免费音乐游戏。它在全世界有上千万的玩家，并拥有上万张谱面。你可以离线或者在线游玩，并与世界各地玩家同台竞技。同时，所有人都可以为他喜欢的歌制作并上传自己的[谱面](/wiki/beatmaps)，然后与全球玩家一同分享！
为喜欢的音乐会不会更好一点

2017-10-01 18:08 UTC, merged