Reporting_Bad_Behaviour / Handling_Foul_Play
osu-translate-zh/osu-wiki pull request #21
Opened 2017-10-05 16:31 UTC by axmmisaka

### Description
Translation of HFP after English version has changed.

### Status
Finished. Awaiting for review.

### Changelog
See changelog of English version - the policy changed hugely.

2017-10-05 17:56 UTC, kj415j45 submitted a review, later dismissed

2017-10-05 17:56 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +如 [规则](/wiki/Rules) 所说，任何形式的对客户端的篡改；改分；使用宏连打出的combo，自瞄以及其他任何帮助玩家打游戏的工具都被认为是作弊。
规则→规章制度

链接与实际标题同步

2017-10-05 17:56 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +## 我朋友因为作弊被封禁了！他们肯定不是挂壁！你们错了！
不是挂壁→没有开外挂

2017-10-05 17:56 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +你可能很难冷静地接受这个残酷的事实，但你得相信工作人员。ppy当然不想破坏大家的友情，但是他也知道人心隔肚皮。即使是那些你永远不会怀疑的那些和你很亲近的人也可能在你和其他人看不见的地方搞小动作。
ppy两头空格

2017-10-05 17:56 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +工作人员不能说他们怎么证明的。公开反制措施会让它们无法在以后监测作弊者。
它们→他们

2017-10-06 00:37 UTC, Baka-D commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +在[这里](/wiki/rules) 仔细地阅读规则并遵守它。
此处用“仔细地阅读并遵守这些[规章制度]”比较合适

2017-10-06 00:48 UTC, Baka-D commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +你应该举报他们并不要在其他地方提及他们。有三种方法可以举报他们：
这四句应为一段话

2017-10-06 07:26 UTC, huoyaoyuan requested changes

2017-10-06 07:26 UTC, huoyaoyuan commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	你借号给别人
将账号借给他人使用
_语气统一一点_

2017-10-06 07:26 UTC, huoyaoyuan commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +冷静.
标点

2017-10-06 07:26 UTC, huoyaoyuan commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，用相机录制打图可以帮你证明清白。
相机不太贴切

2017-10-06 10:50 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +你应该举报他们并不要在其他地方提及他们。有三种方法可以举报他们：
英文上一版本为四句话,意思没变

2017-10-06 10:51 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，用相机录制打图可以帮你证明清白。
bf4圈子里用"录屏",更容易产生歧义
不知有何建议?

2017-10-06 10:52 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +工作人员不能说他们怎么证明的。公开反制措施会让它们无法在以后监测作弊者。
记得原文的"them"指的是反制措施而非工作人员.
英文原文改了 我跟着改成新的了

2017-10-06 10:57 UTC, Baka-D commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +冷静.
32行缺了一句
按en版的话 这个标点是对的(

2017-10-06 11:15 UTC, Baka-D commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
>  不好意思，但如果你被封禁就意味着工作人员百分百确定你在作弊。一个视频不会起什么作用。
这里漏了一句吧,
"上传视频不会对你有所帮助，因为即使是视频也可以被篡改。"

2017-10-06 11:16 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
>  不好意思，但如果你被封禁就意味着工作人员百分百确定你在作弊。一个视频不会起什么作用。
ok 这是新加的没看到

2017-10-08 10:28 UTC, EeyoreRT requested changes
看到文章中Foul play有些翻成了`不正当行为`。感觉还是**作弊行为**比较好？针对指向不公平游戏这一意义。比如在 用户页举报 那一栏中 reporting suspected foul play，还是改一下

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +每个用户只能用**一个**账号，有账号的用户严禁创建新的账号。第一次违规将会以一个时长取决于新建账号数目的禁言惩罚。持续创建新账户的用户除了之前的警告外将会被限制。
--第一次违规者将会受到禁言惩罚（时长取决于新建账号的数目。）【需要拆句子，不然拗口不好理解】
--**不顾警告**继续创建新账户的用户将会被限制 `despite previous warnings`

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +团队不会提供任何和限制有关的“证明”，但所有的封禁都有有理有据的怀疑做支撑。普通用户十分不可能因此类操作被怀疑。
但所有封禁都有**理据做支撑**（不要加上`怀疑`。）

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +**这是举报怀疑不正当行为的推荐方法，因为它可以向对对此类事件负责的团队成员最多信息。**
（漏主要动词，修改多出的字）--因为这种方法可以向对此类事件负责的团队成员**提供**最多的信息。

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +*举报前记得注意选择的模式。*
**举报前记得注意用户页上所显示的是怀疑该玩家作弊的游戏模式。**【这里是指用户页上的四个模式吧，确认是这个模式的页面后再点举报。如果不讲清楚对于读者不太好理解，所以我意译补充了，请参考。如果你觉得不妥，那至少**游戏**这两个字记得加上哦(game mode

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +在谱面网页上，你可以通过点击一个用户分数右侧的 `举报` 来举报在高分榜上的用户。
--**最**右侧。

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +像平板和触屏一样的外设没事。任何降低能力要求的东西则不行。这意味着使用多台电脑，输入分离器或任何像这些东西一样的设备会被认为是作弊。
……**都**会被认为是作弊

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，用相机录制打图可以帮你证明清白。
录屏确实更歧义。强调的是为打图水平的真实性，可否这样：录制**打图过程**可以帮你证明清白。
或者可否用使用比较广泛的 “手元” 这个词？

2017-10-08 10:28 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	持续违反规则，无论它们累积了多少次
持续**多次**违反规则。【建议后面那句不要了

2017-10-08 15:53 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	持续违反规则，无论它们累积了多少次
这里和原版本的区别就是没有限制次数 我想想怎么润色

2017-10-08 15:55 UTC, axmmisaka commented
@EeyoreRT
Foul play包括: 
-	持续违反规则，无论它们累积了多少次
- 	通过建立新的账号回避惩罚
-	将账号借予他人使用
-	开小号
-	作弊（看下面）
不当行为其实我也觉得不是很妥当 但是foul play应该不止指作弊行为
足球竞赛规则里Serious foul play的翻译是严重犯规 但是这里又不合适
个人觉得不正当行为应该大差不差...

2017-10-08 15:57 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +每个用户只能用**一个**账号，有账号的用户严禁创建新的账号。第一次违规将会以一个时长取决于新建账号数目的禁言惩罚。持续创建新账户的用户除了之前的警告外将会被限制。
理解错了...

2017-10-08 16:00 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +*举报前记得注意选择的模式。*
李菊福,我现在也读不懂
我改更具体了些

2017-10-08 16:17 UTC, EeyoreRT commented
你列出来的是这板块的第一段吗？这个不是foul play的定义啊，这是为何受到限制的众多可能原因。注原文：【Why am I restricted?：A user may get restricted if they do any of the following: 1.Continuous……】
 嗯嗯没错foul play就是犯规，作弊，不公平竞赛的意思，我认为没有别的了噢。你再仔细看看原文，尤其是在之前提到的用户页举报那一栏中，只指向游戏中作弊行为。

（不客气ww高兴能帮上忙。

2017-10-08 16:25 UTC, axmmisaka commented
作弊应该是用的Cheating/hacking吧
下文出现了两次foul play指的是作弊 但是这么起标题感觉其它几种被限制的行为就不包含在内了?
回头有空我再想想

2017-10-08 16:45 UTC, EeyoreRT commented
按照原文，大标题是 Handling foul play 没错的。第一块的标题是 Why am I restricted？从而引出第五点hacking or cheating下文基本都讲这个（只顺带提了一笔multiaccouting）。我想官方取这个大标题(HFP)也不一定是起总结这一板块的目的，而是强调这一板块最重要的一个点——就是如何对待游戏内对成绩作弊的行为。所以你不必担忧那前四点行为（基本和account有关）和标题的关系。  
再者往另一个角度想，foul play既然是不公平竞赛，那些开小号在低rank打出高成绩，也确实属于不公平竞赛的一种。所以也说得通。
但如果你觉得作弊这个词冲突了cheating/hacking的翻译，我刚刚想到一个替换的，可否往“成绩造假行为” 这个方向斟酌翻译呢？
【文中一共出现两次foul play，都是在如何举报一栏下的，
--This is the preferred way for reporting suspected foul play
--Your help in spotting foul play is much appreciated】

2017-10-08 17:01 UTC, EeyoreRT requested changes

2017-10-08 17:01 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +每个用户只能用**一个**账号，有账号的用户严禁创建新的账号。第一次违规将会收到禁言惩罚，惩罚的时长取决于新建账号的数目。不顾警告持续创建新账户的用户除了之前的警告外将会被限制。
这里要删除 `除了之前的警告` 啦。`despite……` 翻译成`不顾` 就可以了。这一段，用户知道受到警告惩罚了，还屡教不改，就被限制了。前后文好理解的，不需要补充。

2017-10-08 17:01 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +团队不会提供任何和限制有关的“证明”，但所有的封禁都会有理有据，令人信服。普通用户十分不可能因此类操作被怀疑。
不建议加上`令人信服`这四个字，有点描述色彩浓厚了，会让读者有逆反心理。
可以直接 **但所有的封禁都是有理有据的。**

2017-10-08 17:01 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +*举报前记得在用户页在四种游戏模式中选择玩家作弊的模式。*
这句改得好棒，非常合适ww 我只是来指出typo的^^ （在用户页**的**四种游戏模式中……

2017-10-10 15:54 UTC, axmmisaka commented
Bad behaviour - 恶劣行为
foul play - 不正当行为
如何?

2017-10-11 09:33 UTC, EeyoreRT commented
我觉得不好，这样翻反而颠倒。Bad behavior包括Foul play（图），而Foul play在列出的不正当行为中是最恶劣的一种了（所以官方单独拎出来讲）。【我之前加了个‘游戏不正当行为’ 是强调玩家在游戏过程中的不正当（也就是作弊，只是不想冲突用词）】
![image 1](https://user-images.githubusercontent.com/30562356/31432425-3db572ae-aea9-11e7-875b-395d7a6726d5.png)
尽量遵从原文吧。既然原文中出现两次foul play都是指作弊行为，那么标题的Handling foul play为什么不能翻成作弊行为呢？
整个页面讲的都是作弊，开小号也算边缘作弊，都属游戏内欺骗行为。文中也反复出现cheating这个词，和foul play本身就是相近的词啊，细化了下而已。

2017-10-15 14:43 UTC, axmmisaka commented
手动at EeyoreRT 耽误了 最近忙足球裁判升级没时间搞这个
不公平行为和作弊行为您更倾向于哪个?
- [] 不公平行为
- [] 作弊行为

想了想您说的很有道理 您看哪个更合适我直接改过去

2017-10-16 08:45 UTC, EeyoreRT commented
是说HFP的标题翻法对吗，我倾向`作弊行为`, 更直观【从标题就警醒广大玩家此事的严重性…。反正作弊这个词的定义是：用欺骗的手段做不合法或不合规定的意思。基本也概括了那5项限制原因的行为。您考虑一下w

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	作弊（看下面）
见下文

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +每个用户只能用**一个**账号，有账号的用户严禁创建新的账号。第一次违规将会收到禁言惩罚，惩罚的时长取决于新建账号的数目。不顾警告持续创建新账户的用户将会被限制。
ASC: 粗体标记的两头空格，防止解析错误

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +如 [规章制度](/wiki/Rules) 所说，任何形式的对客户端的篡改；改分；使用宏连打出的combo，自瞄以及其他任何帮助玩家打游戏的工具都被认为是作弊。
超链接两头不需要空格

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +我们采取一击出局政策。作弊人将会在第一次违规后被限制不定长的时间。但如果作弊人申诉成功，团队可以决定解除限制。
作弊者

第二个"作弊人"改成"他"

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +osu!使用与人工确认相结合的自动作弊探测。
注意空格

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +你可能很难冷静地接受这个残酷的事实，但你得相信工作人员。 ppy 当然不想破坏大家的友情，但是他也知道人心隔肚皮。即使是那些你永远不会怀疑的那些和你很亲近的人也可能在你和其他人看不见的地方搞小动作。
即使是那些你永远不会怀疑的和你很亲近的人，也可能在你和其他人看不到的地方搞小动作

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +**这是举报怀疑作弊行为的推荐方法，因为它可以向对对此类事件负责的团队成员提供最多信息。**
怀疑 → 疑似

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +在用户页，把光标移动到他们的头像上后会出现一个 `举报用户` 按钮。写下所有可以证明该用户有作弊行为的证据。
ASC: 代码标记使用原文。新官网不存在的特性以旧官网原文为准

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +在谱面网页上，你可以通过点击一个用户分数最右侧的 `举报` 来举报在高分榜上的用户。
同上

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +我们**不建议**这种举报方法，因为游戏内举报多和聊天有关。
ASC

2017-10-19 17:43 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +	例子：!report this_user 被怀疑作弊
使用代码标记来包裹命令

2017-10-22 15:34 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +	例子：!report this_user 被怀疑作弊
改了
原文如此

2017-10-22 15:35 UTC, axmmisaka commented
Some changes are not made in this moment.
Wait one.

2017-10-23 10:12 UTC, lslqtz commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +osu!使用与人工确认相结合的自动作弊探测。
用逗号是不是比较好？
osu!旁的空格有必要嘛

2017-10-23 10:12 UTC, lslqtz commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +团队不会提供任何和限制有关的“证明”，但所有的封禁都会有理有据，令人信服。普通用户十分不可能因此类操作被怀疑。
十分不可能是不是不太通顺？

2017-10-23 10:14 UTC, lslqtz commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，用相机录制打图可以帮你证明清白。
降低分辨率算改变能力要求嘛？ 🤔

2017-10-23 10:15 UTC, lslqtz commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	持续违反规则，无论它们累积了多少次
多次和持续是不是重复了？

2017-10-25 04:16 UTC, Deardrops reviewed
下面提到的句子，用意译会更加通顺。
改好之后就可以合并了。
感谢付出，辛苦了！

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +我们采取一击出局政策。作弊人将会在第一次违规后被限制不定长的时间。但如果作弊人申诉成功，团队可以决定解除限制。
一击出局最好加上引号

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	持续（无具体次数）违反规则
多次违反规则

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +每个用户只能用 **一个** 账号，有账号的用户严禁创建新的账号。第一次违规将会收到禁言惩罚，惩罚的时长取决于新建账号的数目。不顾警告持续创建新账户的用户将会被限制。
不顾警告继续创建

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +如[规章制度](/wiki/Rules)所说，任何形式的对客户端的篡改；改分；使用宏连打出的combo，自瞄以及其他任何帮助玩家打游戏的工具都被认为是作弊。
任何对客户端的修改；篡改分数；使用宏工具连打或者自动移动，以及使用其他游戏辅助工具的行为都会被认为作弊。

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +如[规章制度](/wiki/Rules)所说，任何形式的对客户端的篡改；改分；使用宏连打出的combo，自瞄以及其他任何帮助玩家打游戏的工具都被认为是作弊。
使用其他—〉其他使用

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +我们采取一击出局政策。作弊人将会在第一次违规后被限制不定长的时间。但如果作弊人申诉成功，团队可以决定解除限制。
作弊人—〉作弊者

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +我们采取一击出局政策。作弊人将会在第一次违规后被限制不定长的时间。但如果作弊人申诉成功，团队可以决定解除限制。
第一个被限制最好加上原文
被限制（restricted）

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +团队不会提供任何和限制有关的“证明”，但所有的封禁都会有理有据。普通用户十分不可能因此类操作被怀疑。
十分不可能 —〉极小的可能性

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +团队不会提供任何和限制有关的“证明”，但所有的封禁都会有理有据。普通用户十分不可能因此类操作被怀疑。
或者改成
普通用户因这类操作被怀疑的可能性是极小的。

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +不好意思，但如果你被限制就意味着工作人员百分百确定你在作弊。一个视频不会起什么作用，因为即使是视频也可以被篡改。
抱歉，一旦你被限制，这就意味着......

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +**这是举报疑似作弊行为的推荐方法，因为它可以向对对此类事件负责的团队成员提供最多信息。**
多了个对字
对负责这类事件的团队成员

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +像平板和触屏一样的外设没事。任何降低能力要求的东西则不行。这意味着使用多台电脑，输入分离器或任何像这些东西一样的设备都会被认为是作弊。
多台电脑，输入分离器或其他类似的东西都会被认为作弊

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +不过除非站在你旁边，不然我们显然很难监视你，但如果你被指控有这种行为，录制带有手元的打图过程可以帮你证明清白。
不过，除非.......

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +如果你违规了，但你想老实交代、金盆洗手，请联系 [accounts@ppy.sh](mailto:accounts@ppy.sh) 然后解释你干了什么。 诚实非常重要，并且这很可能不会造成永久性惩罚。
诚实非常重要，说谎会得到更严厉的惩罚。

2017-10-25 04:16 UTC, Deardrops commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +-	作弊（看下面）
看下面 —〉见下文

2017-10-25 15:45 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/Handling_Foul_Play/zh.md
> +**这是举报疑似作弊行为的推荐方法，因为它可以向对对此类事件负责的团队成员提供最多信息。**
本来是"对(对此类事件负责的团队)提供"
改成"向"了

2017-10-25 15:50 UTC, merged

2017-10-26 11:27 UTC, kj415j45 commented
@axmmisaka 很可惜，你的分支又被squash了。所以说才要求你们使用规范统一的格式来commit……

另外 @Deardrops ，merge commit的格式……