[Reviewing] /wiki/Reporting_Bad_Behaviour/
osu-translate-zh/osu-wiki pull request #22
Opened 2017-10-05 16:37 UTC by axmmisaka

### Description
Translation of RBB. Previous PR is closed due to "spagetti-like branches"?
Anyway, suggestions are followed and adopted.

### Status
Finished. Awaiting for review.

### Changelog

2017-10-05 17:50 UTC, kj415j45 requested changes

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +## 什么是举报系统？
1、2行间空一行

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 在游戏中使用!report命令
ASC: `!report` 两头空格

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +由于osu!游戏内聊天基于[因特网中继聊天](/wiki/Internet_Relay_Chat "因特网中继聊天"), 因此如果用户名中间有空格，那么空格应该替换为下划线``_``。
ASC: `osu!` 两头空格

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +
大量无用空行

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +# 如何举报某人
此处应该是二级标题

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +可以，但是对于对工作人员的投诉建议，建议你联系osu!支持(support@ppy.sh)。
`联系 osu!支持（support@ppy.sh)`

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +和!report命令不同，用这种方法举报用户只需要一种原因和一些（解释原因的）自定义文本。
ASC: `!report` 两头空格

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +举报对大小写不敏感，因此可以像``this_user_name``一样使用小写字母。
ASC:
```
``this_user_name``
```
两头空格

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +![使用!report命令的例子](./img/Report-command.png "使用!report命令的栗子")
栗子→例子

2017-10-05 17:50 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +![记得在这里添加理由！](img/Report-user-2.png "记得在这来添加原因！")
错别字，另外这两个最好使用相同的文字

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +由于osu!游戏内聊天基于[因特网中继聊天](/wiki/Internet_Relay_Chat "因特网中继聊天"), 因此如果用户名中间有空格，那么空格应该替换为下划线``_``。
【 "IRC" 就不要翻译了吧（ 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +和!report命令不同，用这种方法举报用户只需要一种原因和一些（解释原因的）自定义文本。
【 "用这种方法举报用户只需要**选择一种原因并输入一些自定义文本以解释你的原因**。" 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +这种方式和游戏内举报按钮的工作原理相同。
【 这种方式和游戏内举报按钮**效果**相同 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +记得在举报注释中添加细节。
【 "记得**填写具体的举报原因**。" 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +此方式只应用于举报作弊玩家。
【 "**只有在举报玩家作弊时才应使用这种方式**。" 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +这被看做是愤怒地大吵大闹。
【 "**这样会被认为**是**在**大吵大闹。" 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +别担心，除非你滥用举报功能，错误举报会被忽略掉。
【 "**错误举报会被忽略掉，除非你是在滥用举报功能**。" 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +举报一次就够了，但是你一天之内可以举报多次。两到三次应该没问题。
【 "但是你**可以在一天之内**举报多次。" 】

2017-10-06 03:44 UTC, benpigchu commented on wiki/Reporting_Bad_Behaviour/zh.md
> +像骂人一样的大部分私聊中的问题不会被处理。
【 "大部分私聊中的问题，**比如骂人**，不会被处理。" 】

2017-10-06 07:27 UTC, huoyaoyuan commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 在游戏中使用!report命令
标题中可以使用\`\`标记的

2017-10-06 10:23 UTC, kj415j45 commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 在游戏中使用!report命令
iirc，asc中指出标题不应该使用任何标记（除了小图标）

2017-10-06 11:00 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/zh.md
> +此方式只应用于举报作弊玩家。
原文"This should only be used when reporting cheating users." - 举报的是用户吧

2017-10-08 10:33 UTC, EeyoreRT requested changes

2017-10-08 10:33 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +大部分私聊中的问题，比如骂人，不会被处理。
大部分在私聊中**发生**的问题（比如**辱骂行为**），不会被处理。

2017-10-08 10:33 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 发布不合适的内容，例如H图（可疑的和暗示性的也考虑在内）
例如H图**文**   （我理解了上次你说加了个例外的意思ww我还是认为要强调一下，不然很多人会想当然以为对文字要求较宽松。所以加一个字吧

2017-10-08 10:33 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +此系统不仅仅只在游戏内聊天有用，它在其他地方，例如论坛和这个百科里一样适用。
此系统不仅仅只**限于**游戏内聊天

2017-10-08 10:33 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +举报系统是一个用来通知管理员们不正当行为用户并供他/她们采取行动的重要功能。
举报系统是一个用来通知管理员**哪些用户有不正当行为**并供他/她们**对此**采取行动的重要功能。【完善句子

2017-10-08 15:01 UTC, Regraz commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 发布无用内容，例如广告，标题党和推广链接
**发布**搭配**标题党**感觉不太合适，况且标题党与广告和推广链接性质不太一样，因此建议并列来写：发布无用内容，例如广告和推广链接或做”标题党“

2017-10-08 15:01 UTC, Regraz commented on wiki/Reporting_Bad_Behaviour/zh.md
> +这被认为是在愤怒地大吵大闹。
annoying感觉应该翻译成令人讨厌的（地）

2017-10-08 16:10 UTC, axmmisaka commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 发布无用内容，例如广告，标题党和推广链接
ok

2017-10-09 15:58 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +举报系统是一个用来通知管理员们犯有不正当行为的用户并供他/她们对此采取行动的重要功能。
唔这里你没理解我的意思。一般是（通知…什么人…什么事），如果是（通知…什么人…什么人）句子就不通顺了。所以还是：举报系统是一个用来(通知)(管理员们)(哪些用户犯有不正当行为)并供他/她们对此采取行动的重要功能。【因为长句子很容易会不顺，请再参考一下w

2017-10-09 15:58 UTC, EeyoreRT commented on wiki/Reporting_Bad_Behaviour/zh.md
> +### 发布不合适的内容，例如H图、黄文（可疑的和暗示性的也考虑在内）
【H图、文】 就好了，不需要详尽，因为括号里有`可疑暗示性的也考虑在内` ，黄文就已经远过于暗示性的了，并且这个词一般也被理解为文章，考虑到聊天这种情况，还是用大一点范围的表达

2017-10-15 17:29 UTC, kj415j45 approved these changes

2017-10-15 17:31 UTC, merged