[WIP] ranking criteria / osu!catch
osu-translate-zh/osu-wiki pull request #26
Opened 2017-10-09 04:38 UTC by Deardrops

### Description

翻译 ranking criteria，osu!catch 部分

### Status

WIP

### Changelog

2018-01-23 13:32 UTC, frankhjwx reviewed
整体感觉有点机翻，只是粗略看了看

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Jump**：两个物件之间的空隙，需要使用冲刺（dash）来接住两者。
像Jump这个术语，如果是我来翻的话应当是：需要按住加速键来接住两个物件的间距，即**跳**

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Hyperjump**：非常大的空隙，无法用一般的冲刺来接。在游戏中，当第一个物件是发光的时，hyperjump 会在两个物件之间被触发。
**Hyperjump**：红果跳，只按住加速键是接不到的。在游戏中，当第一个物件是发光的时，hyperjump 会在两个物件之间被触发。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Edge Dash**：两个物件之间有比较大的空隙，但是没有达到触发距离，即不会产生 hyperjump。这时，第一个物件必须被盘子的边缘接住，才能最终接住第二个物件。
**Edge Dash**：边缘跳，当两个物件之间距离较大但又未达到红果跳的距离时，第一个物件必须用盘子的边缘去接才能接住第二个物件。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Antiflow**：与玩家正常的移动模式不同的，突然的方向和速度改变。
**Antiflow**：反向梗，即向正常移动方向反方向移动的物件模式。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Edge dash 不能与 hyperjumps 同时使用。** 由于这样的模式需要非常细致的移动能力，会极大地影响玩家的准确度。
**Edge dash 不能与 hyperjumps 同时使用。** 这是因为边缘跳的使用十分考验玩家的移动能力，也会极大地影响玩家的准确度。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Combos 不能过长。** 接住的谱面会堆放在盘子中，可能会阻碍玩家的视线。注意，滑条尾，折返和转盘的香蕉也算作「水果」。应该定时地放置新的 Combos 来清空盘子，避免这种情况。
> 接住的谱面会堆放在盘子中

接到的水果

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **整体难度应该与缩圈速度的值相同。** 这仅仅是一个标准值，因为整体难度不会影响游戏，也不会影响转盘中水果的总数，即不会影响一个难度的最高得分。在两者的值不相同的情况下，整体难度必须小于等于下一个更难的难度。
说实话这种地方我是建议直接用AR和OD来表示，我不知道std那边wiki怎么翻的，在mapper看来AR和OD这两个术语看起来比翻译的要简单一些

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Hyperdashs 应该仅仅在 droplets 或者滑条折返上使用，并且滑条的路径应该较为简单。** 这样可以避免混乱和不合理的滑条移动难度，因为在复杂的滑条轨迹和 hyperdashs 中移动通常很难玩，并且对准确度影响相当大。在滑条折返中的 Hyperdash 不能被使用超过两次，这样的滑条不能被连续地使用。
> 不合理的滑条移动难度……

确定不是机翻吗，难度这两个字可以略去的。

> 因为在复杂的滑条轨迹和 hyperdashs 中移动通常很难玩

自己看看是不是有语病，建议翻成“因为过于复杂的滑条或hyperdash对玩家来说较为困难”

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **在每一个难度中使用相同的滑条速度。** 因为它是音乐本身的属性而不是谱面的属性。但是，简单的难度可以有更低的滑条速度，以减少对新玩家的准确度要求，使他们能跟上歌曲的节奏。使用高滑条速度来提高分数、连击数、难度是错误的做法。
> 使用高滑条速度来提高分数、连击数、难度是错误的做法。

这边倒是有点意译在里面，我倾向于英文说的无意义的说法，因为事实上使用高sv来做低难度的水果图也是可行的。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Hyperdashes 不应该在 hyperjump 的终点在游戏区域的左边缘或者右边缘时使用。** 这会造成不连贯的移动，Catcher 会在移动到游戏区域边缘时强制停止移动。试着在 hyperjump 结束点和边缘间留出至少 16 osu 像素的空间，一般分别为 x:16 或者 x:496。
> Hyperdashes 不应该在 hyperjump 的终点在游戏区域的左边缘或者右边缘时使用。

又是一股机翻的感觉，这句话比较长了，我会建议这么翻：如果一个hyperdash位于游戏区域的左右边缘，那么这个hyperdash是不能使用的。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +#### 规则
我猜其他rc你们也翻的规则，这边rule翻成规则语气太轻了，我觉得说规定比较好。rc里面的rule是严格不能违背的。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   物件密度应该遵循 1/1 模式 - 1/2 或 1/3 模式可以偶尔被使用。
> 1/2 或 1/3 模式可以偶尔被使用。

机翻感，建议翻成“少数情况下可以使用 1/2 或 1/3 的模式”

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   缩圈速度 / 整体难度应该在 4-6 之间。
下面HP和CS都没翻……这儿咋就翻了呢

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **不能使用 Hyperdashs。** 这样保证难度对新人玩家来说可以操纵。难度可以使用（1/1，1/2）规律的 dashing，并且不能连续使用超过 2 次。
> 难度可以使用（1/1，1/2）规律的 dashing，并且不能连续使用超过 2 次。

可以使用1/1与1/2的跳，但不能连续使用超过两次。

翻译的时候还是避免直翻

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **在期望间距的节奏点间的时间间隔大于 125ms 时，更快的 dashes 可以被单独使用（不能与其他 dashes 同时使用）。** 例如，1/3 dashs 可以在 160BPM 的曲子中使用，1/4 dashs 可以在 120BPM 的曲子中使用。
> 在期望间距的节奏点间的时间间隔大于 125ms 时

这话我一眼看过去都没看明白……我觉得这边这么翻比较好“两个note之间间隔时间大于 125ms 时”，是一个意思

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **物体之间必须留出足够的调整时间，转盘的开始和结尾必须清晰易读。** 调整时间长短取决于歌曲的 BPM：
> **物体之间必须留出足够的调整时间，转盘的开始和结尾必须清晰易读。**

理解有点问题，原文的意思是物件和转盘之间的时间间隔

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   物件密度应该遵循 1/1 或 1/2 模式 - 1/3 或 1/4 模式可以偶尔被使用。单独的 1/3 或 1/4 模式不应该超过一个 bar 的长度（分别为 4 和 5 个物件）。
> 1/3 或 1/4 模式可以偶尔被使用。

跟上面同理，写成“少数情况下可以使用1/3 或 1/4 模式”

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   缩圈速度 / 整体难度应该在 6-7 之间。
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **可以使用基本的 hyperdashs （1/1，1/2），但是不能同时使用两者。** Platters 作为 hyperdashing 的介绍，意味着较难的 hypers（比如 1.5x 的移动距离同时不超过触发距离）和与 antiflow 模式组合的 hypers 不能被使用。
> Platters 作为 hyperdashing 的介绍

what the…… 这边我会这么翻，“因为从Platter难度开始才允许使用红果跳，”

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **不能使用 Edge dashes。** 因为它们需要极其细致的时机把握，缺乏经验的玩家一般不具有这样的能力。
> 因为它们需要极其细致的时机把握，缺乏经验的玩家一般不具有这样的能力。

由于边缘跳对精准控制的要求较高，经验较少的玩家一般不具有这种能力。

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **物体之间必须留出足够的调整时间，转盘的开始必须清晰易读。** 调整时间长短取决于歌曲的 BPM：
跟上面一样，理解有点问题

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   物件密度应该遵循 1/2 或 1/3 模式 - 1/4 或 1/6 模式可以偶尔被使用。
> 1/4 或 1/6 模式可以偶尔被使用。

也跟上面一样改

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   缩圈速度 / 整体难度应该在 7-8.5 之间。
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **在期望间距的节奏点间的时间间隔大于 62ms 时，更快的 dashes 可以被单独使用。** 例如，1/6 dashs 可以在 160BPM 的曲子中使用，1/8 dashs 可以在 120BPM 的曲子中使用。
> 在期望间距的节奏点间的时间间隔大于 62ms 时

跟上面一样改

> 1/6 dashs 1/8 dashs

这边是hyperdashes （就算是dash你这也有语法问题）

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **物体之间必须留出足够的调整时间，转盘的开始必须清晰易读。** 调整时间长短取决于歌曲的 BPM：
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   物件密度应该遵循大部分 1/2 + 1/4 或 1/3 + 1/6 模式 - 1/8 模式可以偶尔被使用。
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   缩圈速度 / 整体难度应该在 7-9 之间。
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   Edge dashes 可以被单独地使用（不能和其他 dashes 或 hyperdashes 同时使用）。
> Edge dashes 可以被单独地使用

可以单独使用Edge dashes

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **物体之间必须留出足够的调整时间，转盘的开始必须清晰易读。** 调整时间长短取决于歌曲的 BPM：
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   1/8 和更高的 hyperdashes 不应该在物件对中同时使用。
> 不应该在物件对中同时使用

这边的意思不是同时，而是连续， 整句话的意思是说不能连续用不同尺度的pattern

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   物件密度应该遵循大部分 1/2 + 1/4 或 1/3 + 1/6 模式 - 1/8 模式可以偶尔被使用。
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   缩圈速度 / 整体难度应该在 8-10 之间。
同上

2018-01-23 13:32 UTC, frankhjwx commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   Edge dashes 可以被单独地使用，不能和 hyperdashes 同时使用。
> Edge dashes 可以被单独地使用，不能和 hyperdashes 同时使用。

可以单独使用edge dashes，但不能和hyperdashes连用。

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +**osu!catch Ranking criteria** 是一系列关于创建 osu!catch 谱面的规定和指南。为了使 osu!catch 谱面被 ranked，谱面必须遵循以下列出的标准。**在任何情况下必须遵守规定**，而指南可以在某些的情况下打破。这些例外的情况必须保证有详细的解释，解释为什么指南被打破，解释为什么遵守指南会影响铺面的质量。
**任何情况下都必须遵守规定**,而在*特定*情况下可以打破指南;  
或是  
**规定必须在任何情况下遵守**,但指南可以在*特定*情况下打破

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +整体
##整体

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **每张谱面至少实用两种不同的颜色，并且不能与谱面的背景、故事版、视频的颜色接近。** 这样，玩家始终能看到物件。
实用->要使用  
故事版、视频->故事版或视频 是否更好?  
这是为了让玩家始终能看到物件 是否更好?

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **如果一个红果跳位于游戏区域的左右边缘，那么这个红果跳是不能使用的。** 这会造成不连贯的移动，Catcher 会在移动到游戏区域边缘时强制停止移动。试着在红果跳结束点和边缘间留出至少 16 osu 像素的空间，一般分别为 x:16 或者 x:496。
```
位于游戏区域的左右边缘的红果跳是不能使用的  
```
是否更好?

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +具体难度
```
## 具体难度
```

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **自定义 catchers 应该在皮肤中额外包含元素 `lighting.png`** 添加这个元素是可选的，元素默认拥有 184x184 像素的尺寸，但它可能随着元素的可见性变化。
可以选择是否添加这个元素 是否更好?

2018-01-25 13:36 UTC, axmmisaka commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **不能使用 边缘跳。** 由于边缘跳对精准控制的要求较高，经验较少的玩家一般不具有这种能力。
边缘跳为何有空格?

2018-02-02 17:41 UTC, EeyoreRT requested changes

2018-02-02 17:41 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +**osu!catch Ranking criteria** 是一系列关于创建 osu!catch 谱面的规定和指南。为了使 osu!catch 谱面被 ranked，谱面必须遵循以下列出的标准。**在任何情况下必须遵守规定**，而在特定情况下可以打破指南。这些例外的情况必须保证有详细的解释，解释为什么指南被打破，解释为什么遵守指南会影响铺面的质量。
这和standard那边一样的哦？我的建议还是这样：规定在任何情况下都须遵守，而指南可以在某些情况下打破。但这些例外的情况必须有详尽合理的解释，解释指南被打破的原因，以及为什么你认为遵守指南会影响谱面的整体质量。

2018-02-02 17:41 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +这些术语经常出现在 osu!catch 的难度名中，或者被 Ranking Criteria 所使用。
These terms are frequently appearing when **getting in touch with osu!catch difficulties** AND are also used within the Ranking Criteria.
这些术语**常见于与osu!catch 难度相关的地方**，**也**在Ranking Criteria 中使用。
【这里的`术语terms`仅仅指只出现在`难度名`中吗？

2018-02-02 17:41 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Droplet**：水滴，一个代表滑条主体的小物件。为接住它们会降低你的准确度，但是与前面两种物件不同的是，它不会造成连击中断。
Missing these will reduce your accuracy, **没**接住它们会降低你的准确度

2018-02-02 17:41 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **Combos 不能过长。** 接到的水果会堆放在盘子中，可能会阻碍玩家的视线。注意，滑条尾，折返和转盘的香蕉也算作「水果」。应该定时地放置新的 Combos 来清空盘子，避免这种情况。
--标点符号使用不当。  **注意：滑条尾、**折返和转盘的香蕉也算作……
--**以**避免这种情况。

2018-02-02 17:41 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **每个难度中至少包含一个转盘，以使谱面富有变化，分数有所起伏。** 但是，如果转盘不适合于这首歌中的任何地方，可以不用强行放上一个。
--**尽量在每个难度中都至少使用一个转盘**【Try to have at least one spinner（指南语气

2018-02-02 17:41 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!catch/zh.md
> +-   **OD 应该与 AR 的值相同。** 这仅仅是一个标准值，因为 OD 不会影响游戏，也不会影响转盘中水果的总数，即不会影响一个难度的最高得分。在两者的值不相同的情况下，不能超过下一个难度的 OD。
--as Overall Difficulty does not affect gameplay nor the amount of fruits a spinner has, **just the maximum score of a difficulty.**
……不会影响游戏，也不会影响转盘中水果的总数，**它只会影响一个难度的最高得分值。**【orz这里我理解的完全相反…我不清楚OD会不会影响最高得分，但按照原文该是的。】
--the Overall Difficulty must be less than or equal to the Overall Difficulty of the next **hardest** difficulty.
在两者的值不相同的情况下，**OD的数值**不能超过下一**更高**难度的OD值。【过多的省略会造成意思不明确

2018-02-19 09:53 UTC, merged