[WIP] Installation (wiki/Installation/zh.md)
osu-translate-zh/osu-wiki pull request #30
Opened 2017-10-28 11:22 UTC by lslqtz

2017-10-28 14:49 UTC, Deardrops commented
这 commit message 我要报警了！💢

2017-10-31 05:02 UTC, Deardrops reviewed
苟群主你快回来把这个坑填了，留坑不填祸害万年！

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 双击创建在桌面的 osu! 图标，它位于你的桌面或开始菜单。
`双击新创建的osu!快捷方式，它位于桌面或开始菜单中。`

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 主菜单应会显示出来。你应该登录来玩 osu!(通过单击相应的按钮创建一个)，但是你也可以离线玩 osu!。(所有的成绩将不会提交到数据库)。
怎么感觉这句话是机翻的？
`进入游戏后显示主界面。你可以登陆 osu! 账号（或者点击「创建账号」），也可以离线玩 osu!（所有成绩都不会上传到服务器）。`
不必逐词翻译，注意要让读者容易理解。

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 享受你的 osu! :)
行首空格

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +谱面(osz 文件)是包含歌曲和播放所需要的文件。
`谱面（osz 文件）包含歌曲文件和游戏所必需其他的文件。`

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 你可以前去 [谱面列表](https://osu.ppy.sh/p/beatmaplist). 找一个你喜欢的谱面，点击它的标题，打开其歌曲的网页。
`歌曲的网页` → `谱面网页`

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +  - 如果您选择保存文件，或者您的浏览器不允许你选择打开方式，你可以进入下载目录，然后双击它，osu! 将会自动导入。
`您`和`你`不要混用，统一用`你`

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 你也可以下载 **[beatmap 包](https://osu.ppy.sh/p/packlist)** ，beatmap 包是把一些谱面整合。它们一般都是 zip 或 rar 文件。你可以下载一个你喜欢的压缩程式提取它(例如 [7-Zip](http://www.7-zip.org/))，并导入提取出的 osz 文件。
`beatmap packs` → `谱面集`
参照名词对照表

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 如果你知道如何使用 BitTorrent 客户端，你可以使用 [由社区成员提供的 torrent 文件](https://osu.ppy.sh/forum/t/147478)，这可以让你一次下载许多 beatmap 包。
BT（BitTorrent）客户端

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 你也可以下载 **[beatmap 包](https://osu.ppy.sh/p/packlist)** ，beatmap 包是把一些谱面整合。它们一般都是 zip 或 rar 文件。你可以下载一个你喜欢的压缩程式提取它(例如 [7-Zip](http://www.7-zip.org/))，并导入提取出的 osz 文件。
`压缩程式` → `压缩软件`
这个是繁体中文的说法吧

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +谱面(osz 文件)是包含歌曲和播放所需要的文件。
一律使用中文括号，下面还有几处括号请检查一下

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +  - 对于 AMD HD**** 系列显卡 ，你需要关闭 shaders。
`显卡`后面多了个空格

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +  - sudo apt-get -y install wine
建议下面的几行命令用 `` ` ``括起来

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +3. 让osu! 运行起来。
空格

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> + - 你需要使用 winetricks (wine的一个辅助工具)，你可以在终端输入以下指令来安装它：
空格

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- [点此下载](https://dl.dropbox.com/u/45596631/osudroid1.5.5/osudroid.apk) osu!droid.apk (版本 1.5.5)。
建议换成 dropbox的网页链接。
不然，当版本更新后，这里的链接无法及时更新。

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +如果你正在使用智能手机，你也可以前往 https://osu.ppy.sh，但并不是所有浏览器都支持下载谱面。我们推荐使用 Opera 手机版或 FireFox 浏览器，下载完毕后打开即可。
`但并不是所有浏览器都支持下载谱面。我们推荐使用 Opera 手机版或 FireFox 浏览器，`
这句建议删除掉

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +如果你正在使用智能手机，你也可以前往 https://osu.ppy.sh，但并不是所有浏览器都支持下载谱面。我们推荐使用 Opera 手机版或 FireFox 浏览器，下载完毕后打开即可。
`https://osu.ppy.sh` 用 markdown 超链接表示

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 你可以通过查看[原帖](https://osu.ppy.sh/forum/t/176495)来找到如何在越狱 iOS 7.0.4 设备安装 osu! iPhone的教程。
空格

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +  - 首先，你需要注册(如果你还没有注册)并登录。注册是快速免费的，只有登录后才能下载谱面、在游戏内查看在线排名或与其它游戏玩家聊天，因此你没有理由不注册！
`注册是免费的，只需要几步，只有登录后....`

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +  - 如果你遇到了一个没有在上面列出的错误，你可以前往[问题反馈板块](https://osu.ppy.sh/forum/5)并发表帖子(可能会有其它人同时或已经碰到相关的问题，所以建议你先搜索相关的帖子)。只要清楚地说出你的问题，并提供一个证据来表明这个问题是确实存在的(截图/视频/能重现该问题的操作步骤)，一定会有人来帮助你的！
建议在这里贴上 wiki 中 help center 的链接。

2017-10-31 05:02 UTC, Deardrops commented on wiki/Installation/zh.md
> +- 现在你就可以游玩你的新谱面啦！如果列表中没有出现你导入的谱面，只需在歌曲菜单按下 F5 键，列表会自动刷新。
`现在，你就可以玩这些新谱面啦！`

2017-11-02 03:58 UTC, EeyoreRT requested changes
一些地方强烈建议建议修改

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 主菜单应会显示出来。你必需登录来玩Osu!！(创建一个通过单击相应的按钮),或玩 '离线模式 (所有的成绩将不会提交到数据库)。
**此时会显示**主菜单。**提示**您登陆账户玩osu!（**通过点击相应按钮创建账户。**)
【建议肯定语气。再就是`登陆`并非`玩`的必需条件。括号里语序调整。
【you should **be prompted to** either log in using an osu! account  (create one by clicking on the appropriate button)

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -  - 在线模式会计算你的分数，在全球的排名，并获得排名。
在线模式**会上传你的分数与成绩，并计入到全球排名中。**
【后两句意义重复。离线模式也可以计算分数，在线模式主要着重于记录和将个人成绩上传参与到整体rank中去噢？

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 享受你的Osu！ :)
享受你的osu!体验！:)

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -一个Beatmap是包含歌曲和播放所需要的文件. 包括osz文件。
**一张Beatmap通常是一份osz为后缀的压缩文件，包含了歌曲以及其他体验该图所需要的内容。（如音效，皮肤，视频，背景图）**
【A beatmap is a .osz file containing the song and other files needed to play.
这里play不应该完全指播放。请参考一下这样的翻法，欢迎讨论w

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 前去 [beatmap编目](https://osu.ppy.sh/p/beatmaplist). 找一个你喜欢的Beatmap，点击它的标题，打开其歌曲的网页。
反了。调换顺序。【找一首你喜欢的**歌曲**，点击它的标题**以**打开该**beatmap**的网页。
【Find a song that you like and click on its title to open its webpage

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 如果你不想下载包括视频单击紫色的(No Video)按钮
如果你不想下载beatmap内包含的视频，可单击紫色的(No Video)按钮。
或者：部分beatmaps内包含视频文件，如果不想下载，可单击紫色的(No Video)按钮。
【原翻不通顺。

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 在这点上，有几种方式来获得Beatmaps安装在Osu!上：
**这个时候，可以通过几种方式来将你的beatmaps正确安装到osu!里。**
【**At this point**,there are several ways to get your beatmaps installed in osu!:

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -  - 如果您的浏览器问你:"如何打开此osz文件?"，您应该选择“打开方式: Osu!”如果可以的话,该文件将被下载，Osu！会自动打开并导入文件。
**当您的浏览器询问您该如何处置此文件时，如果可以的话，请选择“用osu!打开”，在下载完毕后该文件会自动通过osu!打开并导入。**
【……asks you what it should do with the file, choose "Open with osu!" if you can.///断句在这里… The file will be downloaded, and……】
顺便这个地方是在说（如何打开osz文件）吗？是说（如何处置该文件？）吧？一种**打开**，一种**保存**。点**打开** (用osu)，它会开始下载，并默认在下载完毕后自动用osu！打开。

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -  - 如果您选择保存文件，或者您的浏览器不给你选择，下载osz文件，进入下载目录，在其上双击它在Osu!自动导入!
如果您选择保存文件，~~或者您的浏览器不给你选择~~，可在**下载完毕后**进入下载目录，找到该文件并双击它在Osu!自动导入!
【第二句不要翻出来了】

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -  - 如果Osu！已经打开，拖动和直接在游戏窗口拖放下载的文件。如果你是精通技术的，要知道，你也可以将你的.osz文件放置在学osu!的“Song”文件夹(默认:Program Files(x86) / (x64)
如果osu!客户端已在**运行**，**只需拖动刚下载好的文件到游戏窗口内自动导入。当然你也可以将下载的osz文件移动（剪切或复制）到osu!目录的songs文件夹下，回到游戏按下F5键**
【`按F5`是加上的，这种移动的方法不是F5才会被刷新吗？感觉需要提醒一下呢？然后tech-savvy那句就不要翻了啊
【if osu! is already opened, drag and drop the newly-downloaded file directly in the game window. If you are tech-savvy, be aware that you can also move your .osz files in the "Songs" folder of osu!'s installation directory (default is Program Files).

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 现在可以玩你的beatmap！在歌曲菜单按F5键，该列表会自动刷新。
现在可以玩你的beatmap**了**！**如果歌曲列表没有自动刷新，试着在游戏内按下F5键。**
Go play your beatmap! Press F5 at the song select screen if the list isn't automatically refreshed.

2017-11-02 03:58 UTC, EeyoreRT commented on wiki/Installation/zh.md
> -- 下载 **[beatmap 包](http://osu.ppy.sh/p/packlist)**.地图包是把几个beatmaps整合。他们一般都是zip或rar档。下载一个你喜欢的压缩程式提取它（例如[7-Zip](http://www.7-zip.org/)），并导入提取.osz文件。
地图包是把几个beatmaps整合。他们一般都是zip或rar档。—— beatmap包是指将一些beatmaps整理合并成后缀为zip或rar的压缩文件。
 They are archive files that combine several beatmaps at once. They generally come as a .zip or .rar archive.

2017-11-02 05:15 UTC, EeyoreRT commented
可能是因为刚睡醒看的…发现我习惯性地从头开始，都没注意到是已经被修改过的区域orz 非常抱歉，我的失误。这样的话刚刚的review随意看看就好了

2017-11-02 09:35 UTC, lslqtz commented on wiki/Installation/zh.md
> -- 主菜单应会显示出来。你必需登录来玩Osu!！(创建一个通过单击相应的按钮),或玩 '离线模式 (所有的成绩将不会提交到数据库)。
改成建议你登录就可以了吧
思考

2017-11-02 09:35 UTC, lslqtz commented on wiki/Installation/zh.md
> -  - 在线模式会计算你的分数，在全球的排名，并获得排名。
是这样，改

2017-11-02 09:37 UTC, lslqtz commented on wiki/Installation/zh.md
> +- 双击创建在桌面的 osu! 图标，它位于你的桌面或开始菜单。
双击创建在桌面上的 osu! 快捷方式？
赶紧加个新不太通顺

2017-11-02 09:38 UTC, lslqtz commented on wiki/Installation/zh.md
> +- 主菜单应会显示出来。你应该登录来玩 osu!(通过单击相应的按钮创建一个)，但是你也可以离线玩 osu!。(所有的成绩将不会提交到数据库)。
然而全部都是机翻的。。

2017-11-02 09:42 UTC, lslqtz commented on wiki/Installation/zh.md
> +谱面(osz 文件)是包含歌曲和播放所需要的文件。
其它我觉得不用强调
好

2017-11-02 09:46 UTC, lslqtz commented on wiki/Installation/zh.md
> +  - 如果您选择保存文件，或者您的浏览器不允许你选择打开方式，你可以进入下载目录，然后双击它，osu! 将会自动导入。
是这样，忘了改

2017-11-02 09:49 UTC, lslqtz commented on wiki/Installation/zh.md
> +- [点此下载](https://dl.dropbox.com/u/45596631/osudroid1.5.5/osudroid.apk) osu!droid.apk (版本 1.5.5)。
原文就是这样的，固定版本。
所以不改比较好

2017-11-02 09:50 UTC, lslqtz commented on wiki/Installation/zh.md
> +如果你正在使用智能手机，你也可以前往 https://osu.ppy.sh，但并不是所有浏览器都支持下载谱面。我们推荐使用 Opera 手机版或 FireFox 浏览器，下载完毕后打开即可。
如果不提供标题的话咋表示来着

2017-11-02 09:53 UTC, lslqtz commented on wiki/Installation/zh.md
> -  - 在线模式会计算你的分数，在全球的排名，并获得排名。
在线模式会上传你的分数，计算你的表现，你将可以查看在线排名
我准备用这个

2017-11-02 09:55 UTC, lslqtz commented on wiki/Installation/zh.md
> -一个Beatmap是包含歌曲和播放所需要的文件. 包括osz文件。
我翻成这样了：
`谱面（osz 文件）是一个包含歌曲文件、游玩所必须的文件以及额外的文件（如皮肤，视频，背景图）的 zip 压缩包。`

2017-11-02 09:56 UTC, lslqtz commented on wiki/Installation/zh.md
> -- 前去 [beatmap编目](https://osu.ppy.sh/p/beatmaplist). 找一个你喜欢的Beatmap，点击它的标题，打开其歌曲的网页。
这是beatmap列表啊，进了那个页面才可以点。。

2017-11-02 09:57 UTC, lslqtz commented on wiki/Installation/zh.md
> -- 如果你不想下载包括视频单击紫色的(No Video)按钮
这样吧：
如果该谱面包含视频，则你可以下载不包括视频的谱面，只需单击紫色的 No Video 按钮即可

2017-11-02 15:08 UTC, kj415j45 commented on wiki/Installation/zh.md
> +谱面(osz 文件)是包含歌曲和播放所需要的文件。
>`` `.osz` ``文件

2017-11-03 14:40 UTC, lslqtz commented
差不多

2017-11-03 14:45 UTC, Deardrops commented on wiki/Installation/zh.md
> +  - Make your request in the [feature requests thread](https://osu.ppy.sh/forum/t/62313).
```
你希望添加新的功能么？
将你的请求在这个请求帖子中告诉我们。
```

2017-11-12 14:19 UTC, merged