[WIP][Filled with legal terms]Legal/Copyright
osu-translate-zh/osu-wiki pull request #31
Opened 2017-10-28 15:10 UTC by axmmisaka

### Description

Chinese translation of Legal/Copyright

### Status

WIP.
The translator will take part in some personal issues day later, so this PR will probably last for very long time.
Feel free to fork this branch and close this PR if you want to, since I may disappear for a long time (or not).

### Checklist 
Translations of a lot legal terms, such as
- [] believes in good faith (a legal translation)
- [] under penalty of perjury (do have a not-that-good translation)
- [] Counter-Notices (what is this?)
and
- [] Whether ppy's address should be translated into Chinese (if anyone wanna really post one they'll probably refer to the English version... That being said the Russian version is not translated.)

2017-10-28 20:08 UTC, benpigchu commented
【 先提一下：非英文版本的法律文档需注明“翻译版不具有法律效力，以英文原文为准” 】

2017-10-29 06:08 UTC, kj415j45 requested changes
空格

2017-10-29 06:08 UTC, kj415j45 commented on wiki/Legal/Copyright/zh.md
> +**邮寄地址**：
直接使用原文

2017-10-29 06:08 UTC, kj415j45 commented on wiki/Legal/Copyright/zh.md
> +#举报版权侵犯
空格

2017-11-01 14:09 UTC, kj415j45 reviewed
空格。。。

2017-11-26 14:06 UTC, merged