People/Community_Contributors
osu-translate-zh/osu-wiki pull request #39
Opened 2017-12-25 18:30 UTC by kj415j45

2017-12-27 18:35 UTC, kj415j45 commented on wiki/People/Community_Contributors/zh.md
> +| [Saten](/users/444506) | Outstanding moderation presence and commitment (30k+ kills). |
commitment是什么操作（

2018-01-06 12:53 UTC, Deardrops reviewed
表格，建议对齐 `|` 符号，方便 md 文件的阅读

2018-01-06 12:53 UTC, Deardrops commented on wiki/People/Community_Contributors/zh.md
> +**社区贡献者** 是对那些向 osu!社区 投入了大量的心血，提供服务，贡献工具和新功能而使许多用户受益的人进行表彰所给予的名牌。这个名牌代表着他们曾为整个社区做出了显著的贡献。
这句最好使用意译，拆分成短句：
`**社区贡献者** 是为 osu!社区 做出突出贡献，投入大量心血的人，他们为 osu! 添加新工具和新功能，使许多用户受益。为了表彰他们曾经做出的突出贡献，为他们授予这个名牌。`

2018-01-06 12:53 UTC, Deardrops commented on wiki/People/Community_Contributors/zh.md
> +与社区贡献者相比， [osu!校友](/wiki/People/osu!_Alumni) 不同的是，后者纪念的是曾经的 osu!团队成员（如 [GMT](/wiki/People/Global_Moderation_Team) ，[QAT](/wiki/People/Quality_Assurance_Team) ，等等），社区贡献者名牌则授予那些在责任之外自发地来帮助改进  *osu!* 和社
`社区贡献者则授予给那些帮助改进  *osu!* 和社区环境的普通玩家。`
中间那个责任之外自发地可以不用翻译出来，前后对比 已经可以表达出这个意思了。
顺带，`名牌`换作`称号`更为合适。
顺带，`Alumni`，zero_wind说翻译为名人堂比较好，或者使用原文（我建议后者）

2018-01-06 12:53 UTC, Deardrops commented on wiki/People/Community_Contributors/zh.md
> +*另见论坛帖子： [osu! community contributors](https://osu.ppy.sh/forum/p/2489459) 。*
`另见` 我都是翻译为 `参见`

2018-01-07 02:31 UTC, kj415j45 commented
@Deardrops 就两列表格，不用对齐了，空格太多麻烦（

2018-01-08 00:04 UTC, EeyoreRT requested changes

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +与社区贡献者相比， [osu!校友](/wiki/People/osu!_Alumni) 不同的是，后者纪念的是曾经的 osu!团队成员（如 [GMT](/wiki/People/Global_Moderation_Team) ，[QAT](/wiki/People/Quality_Assurance_Team) ，等等），社区贡献者名牌则授予那些在责任之外自发地来帮助改进  *osu!* 和社
不赞同楼上Deardrops的句子改法，把freelancers who had go beyond the call of duty整合为'普通玩家'不够贴合原文意思，`玩家`可以保留，’普通’不好说。我感觉原翻很好了，建议保留 `责任之外自发帮助改进……` 的翻法，才能突出社区贡献者的great所在。

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +**社区贡献者** 是对那些向 osu!社区 投入了大量的心血，提供服务，贡献工具和新功能而使许多用户受益的人进行表彰所给予的名牌。这个名牌代表着他们曾为整个社区做出了显著的贡献。
是**指**那些**主动**为osu!社区投入大量心血……
who have taken it upon themselves

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
>  现在拥有社区贡献者名牌的用户：
现在拥有社区贡献者名牌的用户**如下**：

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [akrolsmir](/users/576800) | 开发了 [AIBat](http://osu.ppy.sh/forum/t/55305) 这个最受欢迎的第三方摸图工具 |
Developing and maintaining 开发**维护**了……【看到好几处都是这样，请问后者不翻也是可以的吗？

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [statementreply](/users/126198) | 在 Bug 修复和新功能测试方面杰出的表现以及为制图者及摸图者提供了许多使用功能 |
typo 使用功能--**实用功能**  （utilities

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [Blazevoir](/users/120265) | 疯狂的管理跟踪记录 (粗略地相当于6位管理人员) 并且几乎以一己之力在高峰时段管理 #osu 频道 (9000以上用户) |
**难以置信的管理记录**（粗略可相当于6位管理人员**的工作量**），
【Insane moderation track record (equivalent to roughly 6 staff members)
`track record`就翻成**记录**噢。是指这位Blazevoir一手揽下很多moderation，所以要加上**工作量**才好理解。

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [MillhioreF](/users/941094) | 在 Bug 修复和新功能测试方面杰出的表现以及管理用户支持请求 |
管理--处理。 【然后这bugfix/feature testing and handling user support queries是并列的吧？调下语序加顿号，再用并列词强调一下。 
---在Bug修复和新功能测试方面、以及处理用户支持请求上**均有**杰出的表现。

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [DeathxShinigami](/users/49516) | 3年多默默无闻而又不辞勤劳地管理 [曲包](http://osu.ppy.sh/beatmaps/packs) 并且在几年内管理了月度新谱面排名竞赛 |
**以及数年对月度新谱面排名竞赛的管理**【and several years of managing the beatmap charts.

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [LuigiHann](/users/1079) | 年复一年的服务，包括了设计原创谱面皮肤，发展了 [故事版](/wiki/Storyboards) 使之成为了一种艺术 |
--服务-贡献。更符合此处语境。
--包括**设计了**原创谱面皮肤……
--**推进了 [故事版] 在艺术性上的发展**  或：**推进了[故事版]作为艺术和作图动力的发展。**
advancing storyboarding as an art and motivation，并非一个人`使之成为艺术`，所以不好这样翻。但关于motivion的翻法，我也不是特别确定，会再想想

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [awp](/users/2650) | 早期的社区管理并且在有限的时间中作出了巨大的贡献 |
over the course of **his** time
……并且在**他**有限的时间过程中……

2018-01-08 00:04 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [Charles445](/users/85000) | 多年来以高要求提高作图质量，并在社区的许多相关问题上提供了帮助。 |
--Years of upholding and improving the quality of mapping,
多年来以高要求**维持并不断改善**作图质量的**水准**。【这里应该主要是指整体的水准而非单人，需要把这点翻出来。
--帮助--协助（assistance

2018-01-08 13:33 UTC, EeyoreRT requested changes

2018-01-08 13:33 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [Nwolf](/users/1910766) | 在世界杯的统计与分析中投入了大量的时间 |
在世界杯**竞赛的数据统计**和分析中投入了大量时间

2018-01-08 13:33 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [Evrien](/users/791660) | 在描述及评论玩家表现和基于事件的报道中贡献突出 |
Outstanding performance in casting, commentary, and event-based writeups/recaps
**在直播竞赛，解说，以及事件报道和摘要的撰写方面均表现突出。**

2018-01-08 13:33 UTC, EeyoreRT commented on wiki/People/Community_Contributors/zh.md
> +| [Tom94](/users/1857058) | 在 osu! 的改进中处于核心地位，包括 pp，图形引擎改写，评分系统等许多方面！ |
核心--主干
The mastermind behind **countless improvements**。在osu!**数不胜数的改进过程**中……

2018-01-09 03:01 UTC, Deardrops commented on wiki/People/Community_Contributors/zh.md
> +| [akrolsmir](/users/576800) | 开发了 [AIBat](http://osu.ppy.sh/forum/t/55305) 这个最受欢迎的第三方摸图工具 |
唔，一般网站讲维护，一般的程序讲开发，这里这么用也没有错

2018-01-09 05:20 UTC, Deardrops commented
@kj415j45 atom 编辑器的插件可以自动对齐，如果觉得不合适，我回退掉

2018-01-09 10:19 UTC, merged