一点更小的改动
osu-translate-zh/osu-wiki pull request #4
Opened 2017-08-22 23:51 UTC by lslqtz

改了下BanchoBot的zh.md

2017-08-23 02:32 UTC, Deardrops reviewed
图片和链接中的**介绍文字**请一并翻译为中文。

2017-08-23 02:32 UTC, Deardrops commented on wiki/osu!tourney/zh.md
> +  It is not recommended to change this.
```
`BufferDangerTime`  定义客户端暂停之前的缓冲等待时间，为了等待更多的回放帧。
不建议改变这个。
```

2017-08-23 02:32 UTC, Deardrops commented on wiki/osu!tourney/zh.md
> +- `tourney-title` (可选) - this image will be placed placed on top of your background sprites and will be located at the bottom of your osu!tourney screen.
```
`background-win1` (可选) - 当左边的队伍获胜时，结果页面上的 background 元素会渐变为这个元素。
当离开结果页面时会渐变回 `background` 元素。
如果没有设置这个元素，则会使用 `backgound` 元素。
`background-win1` (可选) - 当左边的队伍获胜时，结果页面上的 background 元素会渐变为这个元素。
当离开结果页面时会渐变回 `background` 元素。
如果没有设置这个元素，则会使用 `backgound` 元素。
`background-win2` (可选) - 当右边的队伍获胜时，结果页面上的背景元素会渐变为这个元素。
当离开结果页面时会渐变回 `background` 元素。
如果没有设置这个元素，则会使用 `backgound` 元素。
`tourney-title` (可选) - 这个图片会放在你的背景元素的顶部，并会放在你的 osu!tourney 屏幕的底部。
```

2017-08-23 02:35 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +  It is not recommended to change this.
翻译不来，就先丢在那里了...

2017-08-23 02:40 UTC, lslqtz commented
还有一堆没翻译。
先咕了

2017-08-23 03:21 UTC, lslqtz commented
翻译完毕（大概）。

2017-08-23 03:45 UTC, lslqtz reviewed
需要帮助翻译

2017-08-23 03:45 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +![When the multiplayer rooms are created correctly, they will be listed instead of the instructions](Osutourneyroomlist.png "When the multiplayer rooms were created correctly, they will be listed ins
需要帮助翻译

2017-08-23 03:45 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +![osu!tourney osu!tourney declares a winner automatically, adds a score and plays another sprite when showing the results screen. Failed players are blacked out](Osutourneyresults.png "osu!tourney de
需要帮助翻译

2017-08-23 03:57 UTC, lslqtz reviewed
需要帮助翻译

2017-08-23 03:57 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +- This is the second or further iteration of the tournament。
需要帮助翻译

2017-08-23 03:57 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +根据您在 `TeamSize` 中定义的值，the left team will occupy the first slots and the right team will occupy the slots right below that。
需要帮助翻译

2017-08-23 11:44 UTC, EeyoreRT requested changes
今天没时间了所以只看了一部分，下次接着来帮忙捉虫！抱歉有些地方我也不太确定所以一起写了看法，请参考一下w

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +根据您在 `TeamSize` 中定义的值，the left team will occupy the first slots and the right team will occupy the slots right below that。
**左侧的队伍会优先被分配前面的格子，右侧的队伍会紧跟其后被分配到剩下的格子。**
（如果感觉非要翻出below that，那就**下面的格子**）

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
>  我们可以奖励profile badges给比赛符合以下标准的第一名获胜者：
复数w参考w：我们可以奖励profile badges给符合以下标准的**第一名胜利方队员们**

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +- This is the second or further iteration of the tournament。
**比赛进行了两轮或两轮以上。**或者：**该比赛已经举行过两次或两次以上。**
【这里我不太确定……iteration是循环，指的是比赛中超过两轮定胜负，还是说这个比赛至少举行过2次呢？ 我偏向后者

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +![osu!tourney osu!tourney declares a winner automatically, adds a score and plays another sprite when showing the results screen. Failed players are blacked out](Osutourneyresults.png "osu!tourney de
**osu!tourney会自动裁定赢家，在显示这轮成绩结果界面的同时给赢家一分并开启下一轮，游戏过程中失败的玩家将无成绩计分或显示。**
【我不是很明白sprite在这里什么意思，结合adds **a** score也就是 score one, 理解成计分1，我估计another应该就是另一轮，这样就说得通了

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +如果您遇到问题，可以阅读下面的故障排除部分，也可以发送邮件至 [tournaments@ppy.sh](mailto:tournaments@ppy.sh)。
**使用者**如果遇到问题，可以阅读下面的‘故障排除’部分
【**users** encountering…… **T**roubleshooting section】 Troubleshooting 最好引号特指一下。

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +**osu!tourney** 是 osu! 的官方多人旁观客户端，您可以使用它观看或直播全部多人房间。
不要**您**吧，因为tourney客户端也不是人人都可以使用的。直接就：可以**用来**观看**和**直播整场**多人游戏比赛**。
【view **and** stream **an entire** multiplayer **match**】

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +![When the multiplayer rooms are created correctly, they will be listed instead of the instructions](Osutourneyroomlist.png "When the multiplayer rooms were created correctly, they will be listed ins
**当多人游戏房间被正确创建后，写着指导示例的地方会显示具体的队伍/歌曲/人数信息。（见图）**
或者：**当多人游戏房间被正确创建后，会如图般列出具体的队伍/歌曲/人数信息，而非示例。**
【这张图上写着：(team1)vs(team2)(tear rain‘歌曲名’)8/16人数

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +我们可以奖励profile badges给比赛符合以下标准的第一名获胜者：
复数噢。我们可以奖励profile badges给符合以下标准的**第一名获胜方队员们**

2017-08-23 11:44 UTC, EeyoreRT commented on wiki/osu!tourney/zh.md
> +- 比赛每年举办四次或更少(季节性)。
建议翻成; 比赛每年举办次数不超过4次（必须季节性）
【这里的季节性是否意思举办频率不能集中，得随着季节周期？比如2个季节一次。总之如果单单翻成`季节性`感觉不好理解

2017-08-23 13:29 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +- 比赛每年举办四次或更少(季节性)。
感觉the left team will occupy the first slots and the right team will occupy the slots right below that还是不好翻译...说下面的话不太合适(?)，说后面的话感觉又像普通一样

2017-08-23 13:30 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +如果您遇到问题，可以阅读下面的故障排除部分，也可以发送邮件至 [tournaments@ppy.sh](mailto:tournaments@ppy.sh)。
用粗体可以不？

2017-08-23 13:38 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +![When the multiplayer rooms are created correctly, they will be listed instead of the instructions](Osutourneyroomlist.png "When the multiplayer rooms were created correctly, they will be listed ins
**当多人游戏房间被正确创建后，列表会显示房间的队伍名称/歌曲/人数信息。**

思考，用指导示例好像不太合适，按图看的话

2017-08-23 13:42 UTC, lslqtz commented on wiki/osu!tourney/zh.md
>  我们可以奖励profile badges给比赛符合以下标准的第一名获胜者：
第一名胜利方队员们...太怪了

2017-08-23 13:43 UTC, user670 commented
翻译建议：This is the second or further iteration of the tournament。->此次比赛至少是该比赛的第二届。

2017-08-23 13:47 UTC, lslqtz commented
还有几条没有翻译

2017-08-23 14:10 UTC, EeyoreRT commented
-**第一名胜利方队员们**太怪，那**冠军方队员们**可不可以呢？主要是强调first place winners
-**前面的格子会按序优先分配给左侧的队伍，紧接其后的格子会分配给右侧的队伍** 主语是谁都没关系，但这样翻below that 可以吗？因为也不确定一个队伍有几个人，所以只能说**紧接其后的格子**了
-不翻译instead of instruction也行的，不影响理解，大家会看到图
-然后粗体来强调更好了！ww

2017-08-23 14:14 UTC, lslqtz commented
胜利方队员们 或 冠军方队员们感觉可以
其实之前提出来主要是以为第一名和们可能有点歧义，或者直接把TeamSize里面的拿出来讲？

2017-08-23 14:54 UTC, lslqtz commented
差不多ok了

2017-08-23 15:30 UTC, kj415j45 requested changes

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +目前，它只是用于 World Cup ，所以行为可能会被限制。
应该不只是世界杯吧(

这里请说大实话

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +**注意：** 要使用 osu!tourney，您需要拥有 supporter 标签。
您需要成为 osu!supporter

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +这是 osu! tourney 客户端的界面。
多余空格。。。

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +**您还可以通过左键单击以增加或右键单击以减少来手动改变队伍得分**
通过左键单击/右键点击以增加/减少得分

通过左键单击以增加得分，右键反之。

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +我们可以奖励profile badges给比赛符合以下标准的冠军方队员们：
冠军队队员

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +- 此次比赛至少是该比赛的第二届。
cmt。。。。。

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +确保您没有 **使用管理员权限** 运行 osu! (除非 osu! 请求以管理员身份运行).
改为加粗“没有”可能更好。。。

2017-08-23 15:30 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +要开始直播, 我们推荐使用 [Open Broadcaster Software](https://obsproject.com/)，但您也可以使用任意您可以使用的直播软件。
您也可以使用您喜欢的直播软件

2017-08-23 15:37 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +目前，它只是用于 World Cup ，所以行为可能会被限制。
原文world cup我也很绝望啊

2017-08-23 15:38 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +这是 osu! tourney 客户端的界面。
我习惯英文和中文加空格了。。哪个地方的多余空格

2017-08-23 15:39 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +**您还可以通过左键单击以增加或右键单击以减少来手动改变队伍得分**
之前翻其它页面，没发现有用/，就没用

2017-08-23 15:58 UTC, lslqtz commented
# **这commit message我喜欢。**

2017-08-24 14:10 UTC, User670 reviewed
#什么是Osu!Tourney ：Osu!Tourney “当前” 是为世界杯设计的。
#设置 ：“全新的Osu!客户端”粗体。同一段下面的`Height`部分“客户端高度”后面加一个句号。
#奖品 ：This is the second or further iteration of the tournament.这句话丢了？
~#故障排除 的第3个：标题的翻译建议：“osu!tourney无法打开，它出现错误信息且/或自己关闭！”~

2017-08-24 15:07 UTC, lslqtz commented
@user670 故意丢的，据kj415j45说CMT好像是例外？
我去改一下其它的。

2017-08-24 15:08 UTC, user670 commented
既然是翻译就不要不尊重原文。又不是自己重写。

2017-08-24 17:01 UTC, kj415j45 approved these changes

2017-08-24 17:01 UTC, kj415j45 commented on wiki/osu!tourney/zh.md
> +### 如何不卸载当前的游戏创建一个全新的 osu!？
osu! 后空格

然后就可以merge了(squash)

2017-08-24 17:01 UTC, lslqtz commented on wiki/osu!tourney/zh.md
> +### 如何不卸载当前的游戏创建一个全新的 osu!？
原来标点后也要加空格。。

2017-08-24 17:12 UTC, merged