BBCode
osu-translate-zh/osu-wiki pull request #43
Opened 2017-12-26 18:05 UTC by kj415j45

Resolve #42 

原PR #9 

等待二次润色

2017-12-26 18:53 UTC, JiaJiaJiang requested changes

2017-12-26 18:53 UTC, JiaJiaJiang commented on wiki/BBCode/zh.md
> +在 osu!web 中，BBCode 被使用在论坛帖子、签名和用户页面中。
osu!web : 原文为`osu!forums`

2017-12-26 18:56 UTC, JiaJiaJiang commented on wiki/BBCode/zh.md
> +**BBCode** 是在 osu!论坛 中使用的一种标记语法。在很大程度上，是网络上绝大多数论坛所支持的文本格式。它是由围绕文本的标签组成的，有时也是属性。
建议 ：
and, to a larger extent, the vast majority of osu! forums on the internet to enable rich text formatting.
并且在大多数情况下，网络上的osu论坛也主要用这种形式来展现富文本。

2018-02-06 05:48 UTC, benpigchu commented on wiki/BBCode/zh.md
> +**非常不推荐**使用这个按钮！使用这个标签的问题是，在玩家获得一个 [osu!supporter 标签](/wiki/osu!supporter) 后，用户名可以被更改。一旦他们更改了用户名，这个链接就会失效。
【 `**非常不推荐**使用这个按钮！`->`**非常不推荐**使用这个标签！` 】

2018-02-07 06:31 UTC, Deardrops reviewed
有的超链接给了两端空格，有的又没有
可以统一一下

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +**BBCode** 是在 osu!论坛 中使用的一种标记语法。并且在大多数情况下，是网络上绝大多数论坛所支持的文本格式。它是由围绕文本的标签组成的，有时也是属性。在 osu!论坛 中，BBCode 被使用在论坛帖子、签名和用户页面中。
`并且在大多数情况下` 去掉
`围绕文本` -> `包围在文本前后`
`有时也是属性` -> `可以包含特定的属性`
`在 osu!论坛 中，BBCode 被使用在论坛帖子、签名和用户页面中。` -> `在 osu! 网站上，你可以在帖子、签名和用户页面中使用 BBCode`

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +## 注
注意

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +虽然帖子编辑器提供了一些基本的格式化工具，但手动编写 BBCode 也是可行的。BBCode 标签是大小写不敏感的。
BBCode 标签对大小写不敏感。

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +例如（注意代码的顺序）：
代码 -> 标签

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +使用比[斜体](#斜体)更**醒目的方式强调**单词或整个段落。
`一个单词或整个段落`
或者改成 `单词或段落`
下同

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 尽量少用这个标签。过度使用可能会给读者造成不适，使文章更难阅读。
过度使用只会适得其反，使文章更难阅读。
下同

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +使用比[粗体](#粗体)*更淡的方式* **强调**单词或整个段落。
更淡的方式 -> 更轻微地
顺带，建议这里把斜体改为粗体

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 尽量少用这个标签。过度使用会削弱强调的效果。
过度使用会削弱强调效果

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +在单词或整个段落的**中间画一条水平线**。
在单词或句子的**中间画一条水平线**

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +在单词或整个段落的**下面画一条水平线**。
在单词或句子的**下方画一条水平线**

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +请参阅 [X11 color names](https://en.wikipedia.org/wiki/X11_color_names#Color_name_chart) 以获取颜色名称的列表。
考虑换成中文参考资料

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - `NUMBER` 是这些数中的一个 （`50` 、`85` 、`100` 、或 `150`）。
数字和中文标点间不要有空格

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +这个标签通常用于隐藏一些大型的或大量的图片。
这个标签通常用于隐藏尺寸很大或者数量较多的图片

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +使给定的文字或段落格式化为引用。
使 -> 将

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +    - 如果你这样做了（当你点击 `Post`），那么帖子将会被发布到当前主题帖中。
如果你这样做了（当你点击 `Post`） -> 当你点击  `Post`，这个帖子将会被引用到当前主题帖中。

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 每个帖子（右下角）有一个引用按钮，它会自动引用用户的文本。
它会自动引用当前楼层

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 这将保留空白的间隔，这意味着除非你手动打乱代码的格式，否则没有一行代码的格式会被打乱。
这意味着除非你自己打乱代码格式，否则每行代码会保持原有的格式

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 要知道，这不会给每个人带来相同的结果。
不同的人可能得到不同的搜索结果
下同

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +只要图像存在于给定的url中，就可以在任何地方插入这些图像。
空格

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +请将图片上传至 [imgur](https://imgur.com/ "imgur") 或 [puush](https://puush.me/ "puush")。一旦图片成功上传，复制粘贴图片标签间提供的直链。另外，一些网站不喜欢直接访问到他们的图片（也被称为热链）。像上面列出的一些网站，极大可能为直链，因为它们是图片分享网站。
一些网站不愿意用户直接访问到他们的图片（直接访问图片也被称为热链）
像上面列出的一些网站，都是直链，因为它们是图片分享网站。

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 如果你有一些大型的或大量的图片，建议把它们放在一个 [折叠框](#折叠框) 里。
如果你图片尺寸很大或者数量较多的话

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 这个标签只适用于铺面板块！
谱面

2018-02-07 06:31 UTC, Deardrops commented on wiki/BBCode/zh.md
> +  - 然而，这个 bug 在新的设计中得到了解决。
~然而~这个 bug 在新版论坛中已经修复。

2018-02-07 09:26 UTC, 1004121460 commented on wiki/BBCode/zh.md
> -- 专用按钮： ![字体大小选项](img/font-size.png)
空格

2018-02-07 09:26 UTC, 1004121460 commented on wiki/BBCode/zh.md
> -- 最早的论坛帖子： [HOW TO: Forum BBCodes](https://osu.ppy.sh/community/forums/topics/445599) by [Stefan](https://osu.ppy.sh/users/626907)
空格

2018-02-07 09:26 UTC, 1004121460 commented on wiki/BBCode/zh.md
> +使用比 [粗体](#粗体) **更轻微地强调**单词或段落。
~~使用~~

2018-02-07 17:30 UTC, Cyanoxygen approved these changes
Small details are corrected (?)

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +**BBCode** 是在 osu!论坛 中使用的一种标记语法。是网络上绝大多数论坛所支持的文本格式。它是由包围在文本前后的标签所组成的，可以包含特定的属性。在 osu! 网站上，你可以在帖子、签名和用户页面中使用 BBCode 。
> 是网络上绝大多数论坛所支持的文本格式。它是由包围在文本前后的标签所组成的，
->
也是被网络上绝大多数论坛所支持的文本格式。它的主体是包围在特定文本前后的标签，可以表示特定的属性。

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +虽然帖子编辑器提供了一些基本的格式化工具，但手动编写 BBCode 也是可行的。BBCode 标签对大小写不敏感。
> 但手动编写 BBCode 也是可行的
->
你也可以手动编写 BBCode

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +在没有选中任何文字的情况下，单击按钮会在光标两边插入标签。在选中文字的情况下，单击按钮会在文本两边插入标签。
插入新行：
在没有选中任何文字的情况下，单击按钮会在光标两边插入标签；\
在选中文字的情况下，单击按钮会在文本两边插入标签。

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +使用比 [斜体](#斜体) 更**醒目的方式强调**单词或段落。
去掉 ` 使用 `

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +  - 如果你选择了一种颜色，请确保它能与背景颜色形成对比，这样能让任何人都可以识别出文本。
` 如果你选择了一种颜色 ` -> ` 如果你更改了某段文本的颜色 `
` 这样能让任何人都可以识别出文本 ` -> ` 这样才能让任何人都辨认出文本 `

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +  - 尽量少用这个标签。过度使用只会适得其反，使文章更难阅读。
认为 ` 尽量 ` 应加一个 `能` （下文均按此修改）

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +  - `HEXCODE` 参数不应该使用引号包围。
` 不应该使用引号包围 ` -> ` 不应该被引号包围 `（下文如有，按此修改）

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +    - 如果参数为一个十六进制数，它必须以`#`开头，然后为 6 个十六进制（0-9，A-F）字符。
删去 ` 一个 `

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +    - 如果参数为颜色名称，它必须为一个有效的 HTML 颜色名。
` 有效 ` -> ` 合法 `

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +  - `NUMBER` 是这些数中的一个（`50`、`85`、`100`、或 `150`）。
要强调 `NUMBER` 是这些数中的一个（`50`、`85`、`100`、或 `150`）。
在 ` 是 ` 之前加 **只能** 。

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +使用 `Monospaced` 字体格式化代码，并将代码放在一个灰色的盒子里。当你为一个项目发布故事版代码或源代码时，这个标签是非常有用的。
*  ` 盒子 ` -> ` 文本框 
* ` 版 ` 书写错误。应为 ` 故事板 `（__Storyboard__）

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +  - 这将保留空白的间隔，这意味着除非你自己打乱代码格式，否则每行代码会保持原有的格式。
这将保留空白的间隔 ->
这将保留一些空白间隔；
删去 `这意味着`

2018-02-07 17:30 UTC, Cinhi commented on wiki/BBCode/zh.md
> +**非常不推荐**使用这个标签！使用这个标签的问题是，在玩家获得一个 [osu!supporter 标签](/wiki/osu!supporter) 后，用户名可以被更改。一旦他们更改了用户名，这个链接就会失效。
问题比较严重。
如果玩家有 [osu!supporter 标签](/wiki/osu!supporter) ，那么该玩家的用户名可以被随意更改。一旦他们更改了用户名，这个链接就会失效。

2018-08-20 09:22 UTC, merged