[WIP] osu!wiki contribution guide
osu-translate-zh/osu-wiki pull request #45
Opened 2017-12-31 01:50 UTC by Deardrops

### Description

### Status

### Changelog

### Checklist 

### Related Issues

2018-01-05 17:49 UTC, kj415j45 requested changes

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +这个问题也被表述为：“我的所有提交都是‘update en.md’”，或者相似的内容。
Update zh.md

另外，这样套引号很奇怪

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +一个有意义的提交信息指别人可以直观地理解你的所有修改，而不需要看 Github diff。提交信息有 72 个字符的限制，所以你需要尽量简洁的描述。如果你在精简信息时需要困难，你需要分割所修改的内容，进行多次提交。**请记住，`Update en.md` 或者相似的句子没有实际价值，因为别人不知道你具体做出了哪些修改，或者修改了哪篇文章。**
使别人

GitHub diff

Update zh.md

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +3. 开一个 pull request。
Pull Request

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +从技术上说，最好的方式是在分支上 squash（折叠）提交，可以不受 Github 网页上折叠提交历史的许多限制。另外，Github 桌面客户端上也无法 squash 提交。
squash（压缩）

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +你从 `osu-wiki` 仓库创建你自己的仓库，相当于保存了一份那个时刻的快照。问题在于，你的仓库不会自动与原始的仓库同步，Github 上也没有为你做这件事的银弹。（注：“银弹”指的是任何情况下都管用的方法，相当于中文常说的“万能药”，这句话的意思是说：没有一个完美的方法可以让两个仓库时刻保持同步。）
这句话的原文的意思是

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +如果没有错误发送，你的 master 分支已经与 `ppy:master` 分支同步，你现在可以从你的仓库的 master 分支创建新的分支，而不会有冲突问题。
没有错误发生

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/GitHub_Desktop/zh.md
> +*这篇文章继续父页面的内容*，假设你即将使用 [GitHub 桌面客户端](https://desktop.github.com)。**你也可以使用其他 git 客户端。** 即使在你本地工作，你仍然需要访问 Github 来开 pull requests，使你的修改生效。
GitHub

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/GitHub_Desktop/zh.md
> +*注意：如果你在 Windows 资源管理器中创建新的文件，请确认 `文件扩展名` 选项已勾选。* 更多介绍：[如何显示或隐藏文件扩展名](https://support.microsoft.com/en-us/help/865219/how-to-show-or-hide-file-name-extensions-in-windows-explorer)
https://support.microsoft.com/zh-cn/help/865219/how-to-show-or-hide-file-name-extensions-in-windows-explorer

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/GitHub_Desktop/zh.md
> +1\. 使用 Windows 资源管理器，你的图片编辑器，和你的文本编辑器创建新文件。如果你想要创建新的文章或者添加新的文章翻译，文件命名请遵循 [文章风格指南 - 本地化](/wiki/ASC/#locales)。
/wiki/ASC/#本地化

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/GitHub_Desktop/zh.md
> +4\. 下一步： [克隆分支](#cloning)。
一律使用翻译后的标题做锚点名称，下面相同的问题不再单独review

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/GitHub_Web_Interface/zh.md
> +*这篇文章继续父页面的内容.* 如果你正在修改多篇文章（包括上传，删除，移动图片或其他文件），请阅读另一篇指南——[GitHub Desktop](/wiki/owcg/GitHub_Desktop)。
如果你打算

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/GitHub_Web_Interface/zh.md
> +*注意：**不推荐**这么做*。因为你只能一次移动一个文件！可能会制造很多“无意义”的提交，让其他审阅人员误解而关闭你的 pull request。
如果这里解析存在问题，尝试使用下划线风格或者标记两头添加空格

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/zh.md
> +4\. 为了解决这个问题，请看[常见问题 § 我的分支过时了（out of date）！](/wiki/owcg/Common_Issues/#my-branch-is-out-of-date!)。
常见问题——我的分支过时了

过期了，可能更好点？

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/zh.md
> +当你创建了 pull request 后，其他 osu!wiki 贡献者可能会审阅你的修改，帮助寻找一些你没有注意到的错误。 **你需要及时修正这些错误，** 否则你的 pull request 可能会被标记为“关闭”！如果你想要别人审阅你的 pull request，你可以在 [osu!dev Discord 频道](https://discord.gg/ppy)中寻求其他人的帮助，或者在 G
可以注明一下：
对于中文文章，你可以通过`@osu-translate-zh`来寻求 osu!中文翻译组织 的审阅。

2018-01-05 17:49 UTC, kj415j45 commented on wiki/osu!wiki_Contribution_Guide/zh.md
> +为了让你的修改可以最终上线 osu!wiki，你的 pull request 需要被合并。一旦你的 pull request 被审阅和批准（approved），你可以在评论区或者 [osu!dev Discord 频道](https://discord.gg/ppy)中请求合并你的分支。一旦分支被合并，你的修改会在 5 小时内上线 osu!wiki。
审阅完成并得到批准（Approved）

2018-01-07 06:25 UTC, kj415j45 approved these changes

2018-01-07 06:25 UTC, merged

2019-09-24 12:32 UTC, pan93412 reviewed
（審核到一半才發現這已經是逾 1 年半的 PR）

2019-09-24 12:32 UTC, pan93412 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +如果有人告诉你要使用有意义的提交信息，或者你的所有提交信息都是一样的，这意味着你当你在网页上移动，编辑或者删除文件时，没有使用有意义的提交信息。
….. 編輯或者刪除文件時，**未**使用有意義的提交信息

2019-09-24 12:32 UTC, pan93412 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +一个有意义的提交信息指别人可以直观地理解你的所有修改，而不需要看 Github diff。提交信息有 72 个字符的限制，所以你需要尽量简洁的描述。如果你在精简信息时需要困难，你需要分割所修改的内容，进行多次提交。**请记住，`Update en.md` 或者相似的句子没有实际价值，因为别人不知道你具体做出了哪些修改，或者修改了哪篇文章。**
... 所以你需要**盡可能使描述簡潔** ...

2019-09-24 12:32 UTC, pan93412 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +为了解决这个问题（同时适用于桌面客户端和网页）:
**若要**解決這個問題（同時適用於 GitHub 桌面客戶端及網頁）：

2019-09-24 12:32 UTC, pan93412 commented on wiki/osu!wiki_Contribution_Guide/Common_Issues/zh.md
> +13. Click `Squash and merge`。
13. 再按一次 `Squash and merge`。