Ranking criteria / osu!standard
osu-translate-zh/osu-wiki pull request #49
Opened 2018-01-24 15:09 UTC by Deardrops

由 Karen 和 regraz 贡献翻译

请让我明天先整理一下格式后再开始 review

2018-01-26 13:27 UTC, EeyoreRT requested changes

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +**osu! Ranking Criteria** 是一系列关于创建 osu!catch 谱面的规定和指南。为了使 osu! 谱面被 ranked，谱面必须遵循以下列出的标准。**在任何情况下必须遵守规定**，而指南可以在某些的情况下打破。这些例外的情况必须保证有详细的解释，解释为什么指南被打破，解释为什么遵守指南会影响铺面的质量。
-`创建osu!catch` 这不是standard的rc吗？
-**规定在任何情况下都须遵守**，而指南可以在某些情况下打破。【保持句式一致，前后更好理解。
-**但**这些例外的情况必须有**详尽合理**的解释，解释**指南被打破的原因**，**以及**为什么**你认为**遵守指南会影响**谱**面的**整体**质量。
【感觉warranted没被翻出来，所以加了个**合理**算意译进去了。

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **![Hard](/wiki/shared/diff/hard-s.png "Hard") Advanced:** 一种结合了 Normal 和 Hard 的中间难度，通常用于填补高难度 Hard 和低难度 Normal 之间的难度跨度。
-A difficulty combining **elements** found in both Normal and Hard difficulties
一种结合了normal和hard**各自元素**的中间难度。
-between **lower-level normals and higher-level hards**.
填补了**更低阶normal和更高阶hard**之间的难度跨度。
【这里最好不使用`难度`这个词，因为hard和normal本身就是**难度**，原文想表达更难的hard和更低难度的normal，引起歧义，至少比较词"更"是一定要加的

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **Overlap:** 物件之间互相堆叠。
Hit objects touching each other where they do not stack.
物件之间互相堆叠**但不完全重合**

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **Slider border:** 用于描述滑条路径的边框，如果滑条因相互交叉而过于扭曲，会更难看清滑条路径。
描述--**描绘** ，**可见**边框。（Visible outline of a slider's path.
滑条因相互交叉**重叠**而过于扭曲 distorted through overlaps（不加重叠也可以，强调一下更好呢？

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **Keysounding:** 使用与音乐很相近的音，或者直接用音乐中的音来作为谱面音效。 这种下音效的做法通常情况下给玩家的打击感很少。
--这种~~下~~音效的做法通常~~情况下~~给玩家的打击反馈感很少。（low feedback to the player.

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +这里会列出 [Ranking Criteria 论坛版块](https://osu.ppy.sh/forum/87) 的最近更新（Recent changes）。按照惯例，这里列出了所有正在讨论的规则，一旦意见达成一致，这些规则将被更新。
Rule proposals as well as suggestions are discussed in the Ranking Criteria Subforum.
**规则的提出及建议**会在[Ranking…版块](https……) 内**进行讨论**
Any rule that went through a discussion and community approval process is listed here **as it has been agreed on in the respective discussion thread**
**这里会列出所有经过分别探讨达成一致意见，并得到了社区认可的规则。**
【原翻感觉有歧义，rc是已经定下来的规则，并不是所有正在讨论的规则，这样说是不是有误导性呢？然后这里我把后面as it has…合并到前半句了，觉得分开更好的话可以考虑这样直译：**这里会列出所有经过探讨并得到了社区认可的规则，它们已在各自的讨论帖中达成了一致意见。**

2018-01-26 13:27 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **除非强制使用默认皮肤，所有难度必须使用至少两种自定义颜色。** 在任何情况下物件颜色不能与背景 / 故事版 / 视频的颜色混合在一起，这是为了确保物件对于玩家来说一直是可见的并且自定义皮肤的颜色不会意外地与背景的颜色混合在一起。
--两种自定义**物件**颜色【`颜色`指向不分明。
--这是为了确保物件……并且**防止**自定义皮肤的颜色意外地与背景的颜色混淆在一起。【通顺

2018-01-26 14:19 UTC, Deardrops commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **![Hard](/wiki/shared/diff/hard-s.png "Hard") Advanced:** 一种结合了 Normal 和 Hard 的中间难度，通常用于填补高难度 Hard 和低难度 Normal 之间的难度跨度。
`Normal < Advanced < Hard`
我倾向于意译出这层意思来：
`一种处在 Normal 和 Hard 中间的难度，填补了两者之间的难度跨度。`

2018-02-02 16:14 UTC, EeyoreRT requested changes
我是从下往上review的，所以有些地方说了'如下'

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **避免看起来相似的 1/1 和 1/2 间距。** 可以用跳在有重音的地方改变间距，但是这些跳看起来应与 1/1 跨度的间距不同。
Spacing variation through jumps on points of emphasis are encouraged, but **only if** these jumps are **recognizably** different from 1/1 gaps.
可以(~~用~~)跳在有重音的地方来改变间距，但是这些跳看起来**一定**要与 1/1 跨度的间距有**明显**不同。
【only if的语气用`应`感觉不够合适。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **物件密度应该主要由 1/2 和偶尔的 1/4 节奏或者更慢的节奏组成。**
Note density should consist of mostly 1/2, occasional 1/4, or slower rhythms.
物件密度应该由**主要的**1/2**节奏**，和偶尔的 1/4 节奏或更慢的节奏**所**组成。【`主要`修饰1/2

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **转盘恢复时间应至少有 1 拍。** 这是为了保证在点击转盘后面的物件前有充足的时间进行准备。
这是为了**确保**在点击转盘后面的物件前**玩家**有充足的时间进行准备。【补充主语，翻译没有问题，只是精益求精下w

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **避免使用小于 2 拍的转盘。** 玩家需要时间来确认他们需要开始转圈。
玩家需要时间来确认他们**得**开始转圈。【避免使用重词

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **避免使用小于 3 拍的转盘。** 玩家需要时间来确认他们需要开始转圈。
和下一样。**得** （have to begin spinning

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **转盘后恢复时间应至少有 2 拍。** 这是为了保证在点击转盘后面的物件前有充足的时间进行准备。
和hard那条一样 **确保**  和主语**玩家**

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **可以出现重叠，但是避免反复交叉使用 1/1 和 1/2 节奏的重叠。** 因为如果这两种节奏看起来是一样的，会给新手玩家造成读图困难。
This may cause reading issues for new players, since two different rhythms are visually the same.
删掉`因为如果`，**由于**这两种节奏**视觉上**看起来是一样的，**这很可能**会给新手玩家造成读图困难。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **可以出现重叠，但是避免反复交叉使用 1/1 和 1/2 节奏的重叠。** 因为如果这两种节奏看起来是一样的，会给新手玩家造成读图困难。
This may cause reading issues for new players, since two different rhythms are visually the same.
删掉`因为如果`，**由于**这两种节奏**视觉上**看起来是一样的，**这很可能**会给新手玩家造成读图困难。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **可以出现重叠，但是避免反复交叉使用 1/1 和 1/2 节奏的重叠。** 因为如果这两种节奏看起来是一样的，会给新手玩家造成读图困难。
This may cause reading issues for new players, since two different rhythms are visually the same.
删掉`因为如果`，**由于**这两种节奏**视觉上**看起来是一样的，**这很可能**会给新手玩家造成读图困难。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **物件密度应该主要由 1/1 和偶尔的 1/2 节奏或者更慢的节奏组成。**
同hard那条：物件密度应该**由主要**的1/1节奏，和偶尔的 1/2 节奏或更慢的节奏**所**组成。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **应使用时间 - 间距等比例设定。** 如果间距明显与其他节奏使用的间距不同的话可以接受适当的变化。当物件之间相隔 1 拍，而且在打图区域内的间距相当远，则间距不需要这样精确。
When hit objects are **more than** 1 beat apart and have **relatively** high spacing on the playfield
当物件之间相隔 1 拍**以上**，且在打图区域内的间距**相对**较远，则…
【然后第一句有点长，加个逗号吗？：……使用的间距不同的话，可以接受适当……

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **避免使用小于 4 拍的转盘。** 玩家需要时间来确认他们需要开始转圈。
如下，**得**

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **转盘后恢复时间应至少有 4 拍。** 这是为了保证在点击转盘后面的物件前有充足的时间进行准备。
如下。**确保玩家**

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **应使用时间 - 间距等比例设定。** 如果间距明显与其他节奏使用的间距不同的话可以接受适当的变化。当物件之间相隔 2 拍，而且在打图区域内的间距相当远，则间距不需要这样精确。
如下。逗号。 **2拍以上** 。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **物件密度应主要由 1/1 和 2/1 节奏或者更慢的节奏组成。**
这里因为1/1和2/1都是mostly了所以不需要像下面两个难度的翻译一样去改它了，保持原翻就好（consist of mostly 1/1, 2/1, or slower rhythms.

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **避免使用不可预见的节奏。** 可以通过使用前后一致的时间线跨度在不同的放置点、时间 - 间距等比例以及不规则节拍上的滑条折返 / 滑条尾建立联系来使节奏看起来更加直观。
可以通过使用前后一致的时间线跨度在不同的放置点、时间 - 间距等比例以及不规则节拍上的滑条折返 / 滑条尾**来相互**建立联系，**使得**节奏看起来更加直观。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **尽量将物件均匀摆放在打图区域内。** 无故集中摆在屏幕的某一个部分的杂乱的物件会使它们显得格外不自然。
无故**将物件集中杂乱地摆在屏幕的某一部分上**会使它们显得格外不自然。（Cluttering hit objects in one section of the screen for no reason will make them stand out unnecessarily.）【使语句通顺

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **当歌曲节奏的优先度不明确的时候，避免跟多种音轨。** 应使玩家能够辨别你跟的是歌曲的哪个部分。
应使玩家能够辨别**谱面配合的**是歌曲的哪个部分。Players should be able to discern what part of the song is being followed.
【其实感觉follow翻译成`跟` 挺贴切的，只是稍稍有些口语化。这里想到另一种翻法供参考一下

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **确保你的转盘不会太长。** 保持转盘长度最长为 5-7 秒；更长的时间会使玩家的手腕疼痛。如果你一定要使用长转盘，请确保它合曲。
Make sure that your spinners are not **unreasonably** long. 确保你的转盘不要无故过长。

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **避免在歌曲的相似部分使用不同的风格。** 基本的间距和节奏应该是相似的，然而物件排列可以有所不同。这是为了保证所有相似部分的节奏和强度能同样地反映歌曲。
使用不同的**作图**风格。（major composition differences

2018-02-02 16:14 UTC, EeyoreRT commented on wiki/Ranking_Criteria/osu!/zh.md
> +-  **所有圆圈和滑条头应放在音乐中明显的音上。** 在没有音的地方放物件会导致节奏不合曲。
指南第一条好像漏掉了吗？这里需要核对一下是否是遗漏
Avoid perfectly overlapping slider bodies in a way that causes reading issues. Doing so can cause sliders to be misread as a circle due to obscuring the slider body.
![image 1](https://user-images.githubusercontent.com/30562356/35742895-e203e396-0876-11e8-8402-f5597c3c15d2.png)

2018-02-19 09:53 UTC, merged