zh-options - progress: 47/451, 10.4%
osu-translate-zh/osu-wiki pull request #52
Opened 2018-01-31 16:59 UTC by Philosyang

### Description
zh-options - progress: 47/451, 10.4%

### Status
WIP

2018-01-31 17:03 UTC, kj415j45 commented
Close osu-translate-zh#51

2018-02-02 11:05 UTC, kj415j45 reviewed
如果我comment是“用途”那里，则先以原文为准。晚些去改表格。

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/en.md
> +![Maintenance icon](img/maintenance.jpg "Maintenance icon")
![image](https://user-images.githubusercontent.com/18349191/35728935-2934a1da-0848-11e8-84d6-ebac526291d0.png)
Rename this img's name to `maintenance.jpg`

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +![设定菜单](img/options_basic.jpg "设定菜单 \(左侧的侧边栏\)")
可能的话，截图全部替换成中文环境下的截图，然后使用 `原文件名-ZH.jpg` 来命名图片。

重复问题不再提及。

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `记住密码`   | 如果勾选，此osu!客户端会记住你的密码。                                    | 复选框 | `开启` |
去掉“此”，31行同

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `密码`       | 输入你关联 _osu!_ 用户名的密码。                                          | 文本   | (空)   |
`输入与你 _osu!_ 帐号对应的密码`

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +未登录的状态下，osu!客户端将把你标记为 "来宾" 且你将无法获取在线成绩或进行[多人游戏](wiki/Multi)。
来宾->游客  ？

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `聊天窗口使用Tahoma字体` | 在[聊天窗口](/wiki/chat console)使用旧字体（Tahoma）来替代当前字体（Aller）。 | 复选框   | `关闭` |
`在 [聊天窗口](/wiki/Chat_Console) 使用旧字体（Tahoma）来替代当前字体（Aller）。`

这里更正了错误的链接，需要同步更新英文版本

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `减少丢帧`        | 感觉经常丢帧的玩家可尝试勾选，调节图像设置来降低丢帧，但是会轻微降低帧数。 | 复选框   | `关闭`   |
调节图像设置来减少丢帧情况

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `击打闪光`    | 在击打提示后方加上一个轻柔的闪光。不会在Kiai关闭。           | 复选框   | `开启`            |
不会在 Kiai时间 关闭

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +如果你打开了`帧数限制`的下拉菜单，你会有以下设定供选择：
？？？？？

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `有时` | 你会在每个季节开始时看到季节性背景。osu!小队会决定何时取消并换回熟悉的背景。 |
osu!团队 会决定何时。。。。。

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> -| `Never`     | You will never see seasonal backgrounds, and defaults will be used in all cases. This means you won't have any animu.
@MegaApplePi "animu"? It should be "anime"?

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `永不` | 你永不会看到季节性背景。这代表你将不会看到任何动漫。                         |
待讨论

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `显示缩略图` | 显示谱面背景图的预览。需要2.2+版本的皮肤支持。 | 复选框 | `开启` |
需要皮肤版本2.2以上并支持

2018-02-02 11:05 UTC, kj415j45 commented on wiki/Options/zh.md
> +| `击打偏差` | 用分数计显示击打准确性。可以显示出玩家是否过早或过晚地击打。          |
准确率？

2018-02-02 12:18 UTC, Deardrops reviewed
- [ ] 中英文空格问题

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +- `季节性背景`功能是在向osu!小队积极反映过后被添加的。
`osu!小队` -> `osu!团队`

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +- `季节性背景`功能是在向osu!小队积极反映过后被添加的。
...在`玩家`向...

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +- 如果你仅在用户名输入了名称，却未输入密码，_osu!_ 会使用该名称保存本地分数。
如果你仅仅输入了用户名，未输入密码

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +## 琐事
其他

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +- `{type}` 是版本种类
版本类型

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +点击版本号会用你的默认浏览器打开该版本的发布附文。
发布附文 -> 更新历史

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +在这里，你可以看到你现在使用的版本号以及你在接收何种版本更新。
何种 -> 哪种

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `Debug_DisableTextRendering`      | 停止更新和渲染文字。               | 复选框 | `关闭` |
文字渲染

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `Debug_DisableSpriteDraw`         | 停止全部图像更新。                 | 复选框 | `关闭` |
停止绘制任何元素

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `Debug_DisableBlendingModes`      | 将全部sprite的blend mode恢复标准。 | 复选框 | `关闭` |
sprite -> 元素，下同

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `屏蔽以下词汇（以半角空格分隔）` | 无视以下词汇。                             | 文本 | （无） |
无视 -> 屏蔽

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `当其他人提到你的名字时播放音效`   | 当其他人在聊天中提到你的名字时将播放一个音效。                                                                                             | 复选框 | `开启` |
将播放一个音效 -> 有提示音

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `从不`           | 从不限制光标离开osu!客户端.                                |
不限制光标离开osu!客户端

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `最高显示星数` | 调整显示谱面的**最高**星数要求。 | 滑条 | `10`   |
其实是无穷大，英文这里也一并改了吧

2018-02-02 12:18 UTC, Deardrops commented on wiki/Options/zh.md
> +| `击打偏差` | 用分数计显示击打准确性。可以显示出玩家是否过早或过晚地击打。          |
下面的内容我帮KJ review了一遍

2018-02-02 12:27 UTC, Philosyang commented on wiki/Options/zh.md
> -| `Never`     | You will never see seasonal backgrounds, and defaults will be used in all cases. This means you won't have any animu.
meme accepted?
[urbanDict](https://www.urbandictionary.com/define.php?term=animu)

2018-02-02 12:45 UTC, Philosyang commented on wiki/Options/zh.md
> +点击版本号会用你的默认浏览器打开该版本的发布附文。
Release Notes的话...
“更新历史”吗
我感觉像是“这个版本我都更新了什么东西”

2018-02-02 13:17 UTC, Philosyang commented on wiki/Options/en.md
> +![Maintenance icon](img/maintenance.jpg "Maintenance icon")
accepted & applied.

2018-02-02 13:17 UTC, Philosyang commented on wiki/Options/zh.md
> -| `Never`     | You will never see seasonal backgrounds, and defaults will be used in all cases. This means you won't have any animu.
btw it should be in the en.md instead of zh.md

2018-02-02 13:19 UTC, kj415j45 commented on wiki/Options/zh.md
> -| `Never`     | You will never see seasonal backgrounds, and defaults will be used in all cases. This means you won't have any animu.
en is there, so I simply comment on old part

2018-02-02 13:35 UTC, Philosyang commented
All reviews before here have been applied except [this](https://github.com/osu-translate-zh/osu-wiki/pull/52#discussion_r165615989) one.

2018-04-06 14:19 UTC, ghost requested changes
~~I'm new to here so correct me if suggestions are not following the standard~~
Also `osu!客户端` or `osu! 客户端` needs discussion

EDIT: All `account` should be translated as `账号`, please fix consistency

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +点击`设定`，在主界面按`O`或者在几乎任何界面按`Ctrl` + `O`即可访问设定菜单并修改 _osu!_ 的设置。
Back-sloping comma (`、`) is recommended.
Need a brighter idea on `in almost any screen` though...

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +当你修改一个含有默认值的设定时，在左侧的灰色竖条会亮成黄色。
Consider `在左侧` → `其左侧` (on _its_ left, I think)

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `创建账户`   | 用你的默认浏览器将你重新定向至[创建账户](https://osu.ppy.sh/p/register)。 | 按钮   |        |
Consider `使用默认浏览器打开[创建账户](https://osu.ppy.sh/p/register)页面。`
~~Also L30: `账号` → `账户`~~

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +你也可以在任何含有玩家名片的界面访问此对话框。
Consider `如果界面上有你的玩家名片，你也可以点击它访问此对话框。`. Current translation doesn't cover "**your** player card".

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `修改头像`     | 修改你的用户头像。（你将被重新定向至osu!网站） | 按钮 |
Consider `（将会打开osu!网站）` if you take the [suggestion above](https://github.com/osu-translate-zh/osu-wiki/pull/52#discussion_r179751377).
Also remove `此` according to https://github.com/osu-translate-zh/osu-wiki/pull/52#discussion_r165612719

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `以原语言显示歌曲信息`   | 谱面会显示他们的"原本"的未经翻译的语言数据，如果可用。                        | 复选框   | `关闭` |
Consider `谱面会显示其未经翻译的“原始”信息（如果有）。`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `正式版（每月更新）`   | 公共发布版本。                                |
`公共` → `公开`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +这部分是关于 osu!客户端 和部分界面的设置。
`appearance` is missing - consider `外观`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `显示帧数（FPS）` | 在屏幕右下方可见 FPS 计数器。                                                    | 复选框   | `关闭`   |
`可见` →  `显示`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `osu!主题音乐` | 启动 osu! 时，主题曲将会播放。一旦歌曲切换，你只能重启 osu! 来重新播放它。         | 复选框   | `开启` |
`在启动 osu! 时播放主题曲。`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `垂直位置`   | 调节宽屏幕模式的垂直偏移。只有在`宽屏幕模式`下才会体现。                       | 滑条     | `0%`   |
`Letterboxing` here means the `不缩放画面` option, not `宽屏幕模式`.
Also ``只有在`宽屏幕模式`下才会体现。`` → ``此选项仅会在`不缩放画面`开启时显示。``

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `显示缩略图` | 显示谱面背景图的预览。需要皮肤版本2.2以上并支持。 | 复选框 | `开启` |
`需要皮肤版本2.2以上并支持。` → `所使用皮肤的版本需要在 2.2 以上。`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `帧数限制`        | 修改帧数限制。参阅下方内容。                                                   | 下拉菜单 | `120FPS` |
Consider `详情见下。` for consistency

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `进度条位置`                         | 设置在哪里显示歌曲进度。详情见下。                          | 下拉菜单 | `右上角(饼状)` |
`how` is missing - consider `设置歌曲进度的显示位置和显示方式。`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `当前皮肤`               | 改变皮肤。下拉菜单的选项会根据`skin/`文件夹的内容改变。(名称会根据他们的文件夹命名)                   | 下拉菜单 | `默认` |
Consider `（显示的名字为目录名）`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `osu!已经是最新版！` | 强制使 osu!客户端 重新检查更新，并下载他们。       | 按钮     |                      |
Consider `强制 osu! 客户端重新检查并下载更新。`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `自动缩放光标`           | 自动根据当前谱面的CS来调节光标大小。                                                                  | 复选框   | `关闭` |
Spaces required around `CS`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `预览皮肤`               | 用auto mod随机挑选一张谱面用当前皮肤播放。模式由谱面选择界面的模式决定。                              | 按钮     |        |
`Auto Mod` (and spaces please)

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `启动Wiimote/TaTaCon支持` | 启用 Wii 太鼓控制器 和 Wiimote 支持。启用前请先确认你的Wiimote已通过蓝牙配对。 | 复选框 | `关闭` |
Spaces around the second `Wiimote`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `Raw Input（鼠标原始输入）`  | 无视Windows鼠标加速及后期处理，直接从硬件（鼠标/手写板）读取坐标。 | 按钮     | 关闭             |
Spaces around `Windows`

2018-04-06 14:19 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `关联到MSN Live状态`     | 你的Windows Live Messenger将显示游戏中播放的歌曲。                                               | 复选框 | `关闭` |
Spaces around `Windows Live Messenger`

2018-04-06 14:36 UTC, SerCom-KC commented on wiki/Options/zh.md
> +| `记住密码`   | 如果勾选，此osu!客户端会记住你的密码。                                    | 复选框 | `开启` |
还有 [51 行](https://github.com/osu-translate-zh/osu-wiki/pull/52/files#diff-6483ab4231921b5c179a5be7439e284aR51)

2019-07-30 15:35 UTC, Drickle commented
Closed due to the file which is already outdated in `master` branch.
Consider updating within modifications.

2019-07-30 15:35 UTC, closed without merging