Glossary
osu-translate-zh/osu-wiki pull request #65
Opened 2018-02-13 12:15 UTC by 1004121460

### Description

翻译 `Glossary` 部分

### Status

WIP

2018-03-28 19:42 UTC, EeyoreRT requested changes
冒昧看了一下已经翻译的部分，提出了一些感觉可以修改的地方供参考ww打扰了ww

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +多年来，osu!社区 采用了自己的一套术语，这些术语可能会使一些新人感到困惑。本页面是对一些术语的汇编，仅供参考。欢迎所有人添加或者编辑本页面。
Additions and edits are always welcome
欢迎对本页面的进一步添加或修改。

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +如果你不能理解这个名词，下面则解释了它的意思：`Abandoned Wasteland` 是一个隐藏的子论坛，关于这个子论坛的说明是：“把我们真正不需要的东西放在这里。” 当一篇帖子是或被称为无用的时候，那么这篇帖子则会被移动到这个子论坛。
去掉`真正`（stuff we don't really need, 这里really放后，它只是个语气词—— 不太需要],[不怎么需要],甚至不翻直接[不需要]都可以。

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +AFK 是一个网络缩写词，它的意思是 _Away From Keyboard（离开键盘或玩家长时间离开）_。举个例子，当一个活动的玩家在他还在登录的时候离开去做别的事情时，_osu!_ 将会把他的状态标记为 AFK 。
它的**字面意思**是_Away From Keyboard（离开键盘），**意味着**玩家长时间离开。
接下来这里有点理解问题 An example of this is when an active user walks off to do something else while they are still logged on.  / **osu! will mark users as "Idle"** if they have been inactive for **some time.**
这里应该是两个句子的意思吗？前一句举例于afk，后一句顺带说了下idle，我的个人理解是这样请参考一下ww：举个例子，当玩家在登陆游戏的状态下长时间离开去做别的事情，这会被标记为afk。而短时间的无动静（或不活跃）osu!会标记为Idle。

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +authentic 意思是一张谱面在特定的阶段从方方面面（歌曲、设置、物件摆放布局 等）都模仿 [DS 游戏](/wiki/DS_games) 。
every aspect of **a specific stage from the DS games** (song, settings, object placement, etc.)
**是一张谱面从方方面面（歌曲……）都模仿[DS游戏]的某一特定stage(舞台/演出/场景?**
【我并不是特别了解DSgames，但单看原文，这里的stage应该指的是DS游戏里的stage，它的意思我更偏向于是‘舞台或演出’的表达而非DS游戏的某一`阶段`。

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +Aspire 是一个制作谱面的 [竞赛](/wiki/contest) ，它鼓励创作者完全忽略 [Rank 标准](/wiki/Ranking_Criteria)。从本比赛中产生的谱面往往是在外观上吸引着玩家，但对普通玩家来说，这些谱面是根本无法正常游玩的。
--鼓励创作者**们**完全忽略…
--……往往是以它的外观和**极限的排列**所吸引着玩家。【这里主要是没有把displays of absolute madness翻译出来，请参考一下ww】
--但对**一般水平的玩家**（average players）来说，这些谱面**通常是**无法正常游玩的。【建议often翻出来，因为也有个例的中等水平玩家很会玩极限图】

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +休息时间是指谱面的某段时间内没有任何的打击物件。在这段时间内，玩家将暂时不会掉血。休息时间通常允许玩家在短时间内进行休息他们的手臂并重新调整他们的输入设备。
--在休息时间中，**玩家不会掉血。**或者**玩家的血条会保持原样不动**
--……允许玩家在短时间内~~进行~~休息他们的手臂并重新调整设备**的位置**。

2018-03-28 19:42 UTC, EeyoreRT commented on wiki/Glossary/zh.md
> +当一位 [作者](/wiki/creator) 把他们的 [谱面集合](/wiki/beatmapset) 制作完后，并准备在世界各地分享他们的成果时，他们必须使用 BSS 提交谱面。当他们这样做的时侯，BSS 将会自动分配以及生成一个帖子，其中包含关于你的谱面集合的信息。BSS 生成的论坛主题可以帮助你从修改者与其他玩你谱面的玩家那里得到一些反馈。最后，你的谱面将会被分别赋予 [谱面 ID](
--制作完后，--制作完成，【`后`和`时`冲突
--BSS生成的论坛主题**贴**可以……
--Lastly, your beatmaps will be given a beatmapID ** and can be commented on during replays; as well as a beatmapSetID.**这里好像漏翻了后半句。

2019-08-04 06:03 UTC, merged

2019-08-04 06:03 UTC, Drickle commented
Merge first, resolve today

2019-08-04 06:22 UTC, Drickle commented on wiki/Glossary/zh.md
> +authentic 意思是一张谱面在特定的阶段从方方面面（歌曲、设置、物件摆放布局 等）都模仿 [DS 游戏](/wiki/DS_games) 。
我觉得把 `特定的阶段` 改成 `某个地方` 比较合适，找你这么理解的话可能翻译就会很模糊了