Chat Console translate complete.
osu-translate-zh/osu-wiki pull request #73
Opened 2018-04-05 14:20 UTC by Cyanoxygen

| Status | Reviewing |
|--- | --- |
  
Translation complete .
Now requesting review.
~~No changes for 2 months~~, and today finished it

**NOTE:** If any problem I will fix it on **weekends**.

2018-04-06 12:36 UTC, EeyoreRT requested changes

2018-04-06 12:36 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +在 *osu!* 的绝大多数界面中，你都可以按下 `F8` 或者点击屏幕右下角的 `Show Chat` 按钮以将聊天面板叠加在屏幕的下半部分。
屏幕的**下方**。 【严谨地说并没有`一半`啦，不好直翻**下三分之一的部分**的话，建议就直接**下方** (on the lower third of the screen

2018-04-06 12:36 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   不同颜色的用户名代表不同类型的玩家。
这里建议直翻，把下面这些包括supporter和nonesupporter都意译归类到`不同类型的玩家`不太合适，它主要是强调颜色的意义，请参考一下：**用户名的不同颜色代表着不同的含义**。 或者 ……**有着**不同的含义
The colours of the user names mean different things.

2018-04-06 12:36 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +| **绿色**   | 如果一行消息中出现你的用户名或者某个关键字，你的用户名就会被绿色的高亮标记。这个消息还会单另出现在 `#highlight` 频道中。 |
-- **or certain keywords that you have added to trigger a "highlight.** 这句没翻出来。 参考：**或者某个你添加的可触发高亮标记的关键字词。**
--A **COPY** of the message will also appear in a **DEDICATED** channel,#hightlight, which contains all of these lines.（这里没翻出'只有玩家自己才看得到属于自己的highlight频道的' 的这个意思。所以建议补一句比如：**该高亮消息的副本也会以出现在`#highlight` 频道的形式单独发送给你。**

2018-04-06 12:36 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   点击 `Show Ticker` 按钮将在聊天面板隐藏时，在屏幕底部一行显示当前频道里最新的消息。
……**可在**聊天面板隐藏**不可见的情况下**，在屏幕最底部一行显示当前频道里最新的消息。【这里用`将，时`感觉语意不够清晰，请参考一下ww然后建议翻出not visible

2018-04-06 12:38 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +在 *osu!* 的绝大多数界面中，你都可以按下 `F8` 或者点击屏幕右下角的 `Show Chat` 按钮以将聊天面板叠加在屏幕的下半部分。
- [x] 采纳

2018-04-06 12:42 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   点击 `Show Ticker` 按钮将在聊天面板隐藏时，在屏幕底部一行显示当前频道里最新的消息。
- [x] 采纳

2018-04-06 13:52 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   不同颜色的用户名代表不同类型的玩家。
- [ ] 有待斟酌
对了， `所有已加入的频道` -> `所有加入的频道和私信` 合不合适？

2018-04-07 13:39 UTC, EeyoreRT requested changes

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +你可以在 *osu!* 的绝大多数界面中按下 `F9` 或者在启动屏幕按下屏幕右下角的 `Online users` 以打开扩展聊天面板。与聊天界面不同的是，在线玩家面板占用了屏幕的三分之二，显示着目前 *osu!* 所有在线玩家的一些信息。
--at the lower right of the Intro Screen 把Intro screen 翻成`启动屏幕`不太合适，因为这四个字容易误解成一个动作而非名词，有两个动词（`启动，按下`）连续，造成语句不顺。建议修改一下ww请参考：**或者点击位于右下角引导窗口的 `Online users`按钮**以打开扩展聊天面板。
--**展示**着 *osu!* **目前**在线玩家的一些信息。

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +每一个当前已经登录 osu! 的玩家都会在扩展聊天面板中以一个小方格的形式出现。 一般它里面包括该玩家的基本信息（用户名、 Ranked 谱面总分、排名、准确度、游玩次数以及该玩家的头像，如果有）。当鼠标指针处在这个方块上的时候，它就会显示另外一些信息（用户名、排名、头像、当地时间、时区、所在国家；如果玩家同意的话，还可以显示具体位置以及玩家正在做什么）。
--**它会默认展示该玩家的基本信息**【By default it displays
--这里的if any是特指玩家有无头像。建议头像后不要逗号，加一个方括号，这样就知道if any是特指avatar的。或者干脆不要翻。我暂时也没有想到更好的方法ww但如果直接在句尾直译 如果有，会比较突兀，请斟酌一下。
包括后面再次出现的**avatar if any** 也可以采取这种翻法：**头像[如果玩家有设]、** （或者直接**如果玩家有**

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   “ 好友 ” 分类下的玩家数量仅限于你的好友数量；
Friends only limits the display to your friends. 着重在`数量`上感觉有歧义，不妨考虑这样：**好友分类下仅会展示你的在线好友玩家。**

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   锁定面板可以防止面板上的玩家们跳来跳去，也可以阻止显示新登录的玩家；
`阻止新登陆的玩家`吗？感觉话没说完呢？ww 
Lock Panels stops the panels from jumping round this also includes new users

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   点击 `Show Ticker` 按钮将在聊天面板不可见的情况下，在屏幕最底部一行显示当前频道里最新的消息。。
两个句号噢

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   这一排选项卡展示着所有已加入的频道。仅需在某个选项卡上点一下，就能切换到你想聊天的那个频道。点击 `New` 将显示一个所有可加入频道的列表。
这里关于您说的改为 `所有加入的频道和私信`  我同意您的前半部分改法。因为感觉**available** channel 翻成 `已加入`不太贴切，去掉`已`就可以涵盖两种情况了。
但是否要意译`私信`我觉得不需要www因为看原文这里有张图，上面也都是示例列出了`频道`，也就是说这一部分讲的都是channel相关。chat会在下一节细讲，所以我认为`私信`不需要意译出来ww

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   点击 “ 世界地图 ” 可以查看玩家都在哪里登录；
a world map that shows where everyone is.
点击 “ 世界地图 ” 可以**查看世界各地的玩家们**；

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   点击某个标签页可以将所有登录的玩家按相应的顺序排列；
这里感觉有理解歧义。应该指的是这几个**分类**（见图）而不是`顺序`, 【Click on a tab to sort user panels according to that attribute.】
![image](https://user-images.githubusercontent.com/30562356/38455498-d85eca6a-3aab-11e8-84af-af0759e098fd.png)

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   点击 `Show Ticker` 按钮将在聊天面板不可见的情况下，在屏幕最底部一行显示当前频道里最新的消息。。
两个句号噢

2018-04-07 13:39 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   点击 `Show Ticker` 按钮将在聊天面板不可见的情况下，在屏幕最底部一行显示当前频道里最新的消息。。
多了一个句号ww

2018-04-07 14:15 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   锁定面板可以防止面板上的玩家们跳来跳去，也可以阻止显示新登录的玩家；
应该在后面加上 `出现在面板中` 就对了
- [x] 采纳

2018-04-07 14:16 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   点击 “ 世界地图 ” 可以查看玩家都在哪里登录；
- [x] 采纳

2018-04-07 14:19 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   点击某个标签页可以将所有登录的玩家按相应的顺序排列；
当时的时候实在是不知道该写什么了 😦 抱歉抱歉哈
- [x] 采纳

2018-04-07 16:52 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   这一排选项卡展示着所有已加入的频道。仅需在某个选项卡上点一下，就能切换到你想聊天的那个频道。点击 `New` 将显示一个所有可加入频道的列表。
我觉得还是加上会比较好。看下 @Deaddrops 怎么说 :thinking:

2018-04-08 04:48 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +-   这一排选项卡展示着所有已加入的频道。仅需在某个选项卡上点一下，就能切换到你想聊天的那个频道。点击 `New` 将显示一个所有可加入频道的列表。
如果是觉得`这一排选项卡展示的`不光光是频道也有**私信**这样才严谨。那你不妨换一个讲法，颠倒一下语序：**所有可加入的频道会在这一排选项卡展示。** 这样就不冲突了，只是讲述了选项卡的其中一个功能，也符合它这一小节主要是着重在讲available channel的用意。 
原文示例图：
![image](https://user-images.githubusercontent.com/30562356/38463338-2229f7bc-3b2b-11e8-8a9f-252e2d0f48f3.png)

2018-04-08 06:11 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   这一排选项卡展示着所有已加入的频道。仅需在某个选项卡上点一下，就能切换到你想聊天的那个频道。点击 `New` 将显示一个所有可加入频道的列表。
好！你的这条建议太棒啦！非常感谢😄

2018-04-09 13:59 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +每一个当前已经登录 osu! 的玩家都会在扩展聊天面板中以一个小方格的形式出现。 一般它里面包括该玩家的基本信息（用户名、 Ranked 谱面总分、排名、准确度、游玩次数以及该玩家的头像，如果有）。当鼠标指针处在这个方块上的时候，它就会显示另外一些信息（用户名、排名、头像、当地时间、时区、所在国家；如果玩家同意的话，还可以显示具体位置以及玩家正在做什么）。
**头像 - 如果有**
看看这条合不合适

2018-04-09 14:00 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   “ 好友 ” 分类下的玩家数量仅限于你的好友数量；
- [x] 棒极了

2018-04-09 14:01 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   这一排选项卡展示着所有已加入的频道。仅需在某个选项卡上点一下，就能切换到你想聊天的那个频道。点击 `New` 将显示一个所有可加入频道的列表。
**所有当前加入的频道会在这一排选项卡展示。**
🤔

2018-04-09 14:08 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   点击某个标签页可以将所有登录的玩家按相应的顺序排列；
按照这几个标签的作用来讲，有分类也有类型
干脆都写上了：**分类或类型**

2018-04-09 14:13 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +-   点击 “ 世界地图 ” 可以查看玩家都在哪里登录；
**点击 “ 世界地图 ” 将会展示一幅标示玩家登录位置的地图；**
🤔

2018-04-09 14:15 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +你可以在 *osu!* 的绝大多数界面中按下 `F9` 或者在启动屏幕按下屏幕右下角的 `Online users` 以打开扩展聊天面板。与聊天界面不同的是，在线玩家面板占用了屏幕的三分之二，显示着目前 *osu!* 所有在线玩家的一些信息。
**主屏幕**还是比较不错的

2018-04-10 02:14 UTC, Deardrops approved these changes

2018-04-10 02:14 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +-   所有当前加入的频道均会在这一排选项卡中显示。仅需在某个选项卡上点一下，就能切换到你想聊天的那个频道。点击 `New` 将显示一个所有可加入频道的列表。
```
点击 `New` 将显示一个列表，包含所有可加入的频道。
```

2018-04-10 02:14 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +| **红色**   | [社区管理团队](/wiki/People/Global_Moderation_Team/ "社区管理团队") 或 [质量保证团队](/wiki/People/Quality_Assurance_Team/ "质量保证团队") 的成员  |
质量保障团队
参考 [名词对照表](https://docs.google.com/spreadsheets/d/1zhUP0qekKRUWb1Mu-P89mwu_HcPBen5FoGPqD2MkI7k)

2018-04-10 02:14 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +-   点击 `Auto-Hide` 按钮将在游戏时自动隐藏聊天面板 （除谱面的前奏、休息时段和结尾外）
结尾句号

2018-04-10 02:14 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +| ![玩家离开了电脑](Chat_Console-Afk.png "玩家离开了电脑")                                                | 黑色 - 玩家目前不活跃或者离开了电脑 （ AFK ）                                                                  |
结尾句号

2018-04-10 02:14 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +| `Ctrl` + `C` / `V`        | 复制 / 粘贴                                              |
ditto

2018-04-10 05:42 UTC, kj415j45 reviewed
图片命名格式好像不对？（看看 ASC/图片篇 ？）

2018-04-10 06:48 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +| **红色**   | [社区管理团队](/wiki/People/Global_Moderation_Team/ "社区管理团队") 或 [质量保证团队](/wiki/People/Quality_Assurance_Team/ "质量保证团队") 的成员  |
咦，难道我打错了嘛...
😅

2018-04-10 06:53 UTC, Cyanoxygen commented
emmm，我还要重新截图看起来

2018-04-12 15:01 UTC, EeyoreRT commented on wiki/Chat_Console/zh.md
> +每一个当前已经登录 osu! 的玩家都会在扩展聊天面板中以一个小方格的形式出现。 一般它里面包括该玩家的基本信息（用户名、 Ranked 谱面总分、排名、准确度、游玩次数以及该玩家的头像，如果有）。当鼠标指针处在这个方块上的时候，它就会显示另外一些信息（用户名、排名、头像、当地时间、时区、所在国家；如果玩家同意的话，还可以显示具体位置以及玩家正在做什么）。
我觉得你这样改可以ww用横杠比用逗号好，有特指的意思

2018-05-27 15:08 UTC, Cyanoxygen commented
`/away` 那条翻译不准确。紧急修补一下

2018-05-28 04:22 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +| ![玩家正在更改谱面](Chat_Console-Modding.png "玩家正在更改谱面")                | 绿色 - 正在更改别人的谱面。                                                             |
Mod指的是看别人的谱面，提出修改建议。
这里用`更改别人的谱面`不合适。

2018-05-28 04:22 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +5.  `加为 / 删除好友`：添加该好友到你的好友列表，或者将其从中删除。
添加 / 删除好友

2018-05-28 04:22 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +6.  `举报玩家`：举报玩家不正当的行为。如无其他说明，请勿使用！你可以由于该玩家的一些行为而在游戏中举报，但在论坛中亦可如此。
`举报玩家不正当的行为。也可以在论坛中举报玩家。`
这里不必逐字翻译。

2018-05-28 04:22 UTC, Deardrops commented on wiki/Chat_Console/zh.md
> +|`/np`| 发送你当前所听的 / 所玩的歌曲。| `/np`| （ 游戏时 ） * John is playing [Peter Lambert - osu! tutorial\[Gameplay Basics\]](https://osu.ppy.sh/b/22538) [Game Modes](/wiki/FAQ#alternative-game-modes) \~[Relax/Auto
正在听的 / 玩的 歌曲

2018-05-28 12:04 UTC, Cyanoxygen commented on wiki/Chat_Console/zh.md
> +5.  `加为 / 删除好友`：添加该好友到你的好友列表，或者将其从中删除。
typo

2018-05-28 13:46 UTC, merged