[Review]zh-privacy
osu-translate-zh/osu-wiki pull request #81
Opened 2018-12-01 17:29 UTC by axmmisaka

咕咕咕咕大半年,一晚上搞定

2018-12-02 03:09 UTC, Baka-D requested changes

2018-12-02 03:09 UTC, Baka-D commented on wiki/Legal/Privacy/zh.md
> +为了向您提供这些服务，我们必须经常手机、储存和传输个人信息。我们在运营 osu! 的各个方面力争尽可能透明，而这个隐私政策将会让我们离这个目标更近。
```suggestion
为了向您提供这些服务，我们必须经常收集、储存和传输个人信息。我们在运营 osu! 的各个方面力争尽可能透明，而这个隐私政策将会让我们离这个目标更近。
```

2018-12-02 03:09 UTC, Baka-D commented on wiki/Legal/Privacy/zh.md
> +你好，我是 Dean（也叫 peppy），我是你的数据控制员。如果你有任何隐私问题或要求行使您的法律权利，请不要犹豫并使用以下方式与我联系。
之前好像说过wiki里统一第二人称用"你", 不知道在本页面是否适用。单个页面内应该统一一下人称用语。
```suggestion
您好，我是 Dean（也叫 peppy），我是您的数据控制员。如果您有任何隐私问题或要求行使您的法律权利，请不要犹豫并使用以下方式与我联系。
```

2018-12-02 04:39 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +你好，我是 Dean（也叫 peppy），我是你的数据控制员。如果你有任何隐私问题或要求行使您的法律权利，请不要犹豫并使用以下方式与我联系。
![PayPal 的法律文本](https://user-images.githubusercontent.com/18349191/49335764-fe4a2280-f62e-11e8-8773-cfb9e13f7025.png)
![百度的法律文本](https://user-images.githubusercontent.com/18349191/49335767-0e620200-f62f-11e8-9d87-1f44cf600517.png)

PayPal 与百度的法律文本都是使用您，本文也是法律文本，因此倾向使用“您”

2018-12-02 05:26 UTC, axmmisaka commented on wiki/Legal/Privacy/zh.md
> +你好，我是 Dean（也叫 peppy），我是你的数据控制员。如果你有任何隐私问题或要求行使您的法律权利，请不要犹豫并使用以下方式与我联系。
全部用您了

2018-12-02 06:10 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +osu! 向全世界几乎所有国家的用户提供各种服务，包括富有生机的社区和许多让用户通过如用户资料、谱面（游戏层面）、论坛、私人信息、游戏内聊天和回放评论这类方式向其它用户分享他们创造力的机会。
```suggestion
osu! 向全世界几乎所有国家的用户提供各种服务，包括富有生机的社区和许多让用户通过如用户资料、谱面（游戏关卡）、论坛、私人信息、游戏内聊天和回放评论这类方式向其它用户分享他们创造力的机会。
```

2018-12-02 06:10 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +这份文档用于描述我们在我们的网络中收集什么信息，以及在使用我们的产品和服务时，我们如何使用那些信息和我们向您提供哪些控制您个人信息的选项。
```suggestion
这份文档旨在描述我们在我们的网络中收集什么信息、在使用我们的产品和服务时，我们如何使用那些信息以及向您提供哪些控制您个人信息的选项。
```

2018-12-02 06:10 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +通过使用我们的服务，您确认您以阅读并了解我们的[服务条款](/legal/terms)以及这个隐私政策，包括我们如何和为何使用您的信息，以及您对服务的使用受到适用的服务条款和隐私政策的限制。如果您不希望我们收集或处理在此描述的您的个人信息，您有几种选择，包括限制我们收集的您的信息，或不使用我们的网络或产品及服务。
```suggestion
通过使用我们的服务，您确认您已阅读并了解我们的[服务条款](/legal/terms)以及这个隐私政策，包括我们如何和为何使用您的信息，以及您对服务的使用受到适用的服务条款和隐私政策的限制。如果您不希望我们收集或处理在此描述的您的个人信息，您有几种选择，包括限制我们收集的您的信息，或不使用我们的网络或产品及服务。
```

2018-12-02 06:10 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +例如，当您上传一个谱面并且其“审核通过”，其将成为广大用户群体得分的基准。此时，删除谱面的选项将不可用。
Ranked 暂未翻译，考虑使用原文？

`it becomes the basis for the user base at large to achieve scores on` 这句的翻译感觉很拗口（

2018-12-02 06:10 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +此过程的主要目的是保持公平的排名系统并帮助我们通过辨识是否您的账户在可疑位置登录加强账户安全。此过程是私人的，并只在认为相关时保存。它还是不可转移的，在 osu! 生态系统外没有意义。
```suggestion
此过程的主要目的是保持公平的排名系统并帮助我们通过辨识是否您的账户在可疑位置登录加强账户安全。此过程是私密的，并只在认为相关时保存。它还是不可转移的，在 osu! 生态系统外没有意义。
```

2018-12-02 06:10 UTC, kj415j45 commented on wiki/Legal/Privacy/zh.md
> +我们同样时常持续地和自动地清除数据以只保留履行我们的合法商业利益所需的历史数据。
```suggestion
我们同时在持续地自动地清除数据以只保留保障我们的合法商业利益所需的历史数据。
```

`perform` 的翻译待定

2018-12-02 06:25 UTC, axmmisaka commented on wiki/Legal/Privacy/zh.md
> +这份文档用于描述我们在我们的网络中收集什么信息，以及在使用我们的产品和服务时，我们如何使用那些信息和我们向您提供哪些控制您个人信息的选项。
(This document aims to describe {what information we collect on our network}) and ([in the use of our products and services], {how we use that information} and {what options we offer you to control your personal information.})
原文层次应为如此

2018-12-02 07:17 UTC, axmmisaka commented on wiki/Legal/Privacy/zh.md
> +我们同样时常持续地和自动地清除数据以只保留履行我们的合法商业利益所需的历史数据。
没找到perform interest这种表述

2018-12-02 07:17 UTC, axmmisaka commented on wiki/Legal/Privacy/zh.md
> +例如，当您上传一个谱面并且其“审核通过”，其将成为广大用户群体得分的基准。此时，删除谱面的选项将不可用。
changed

2018-12-03 11:34 UTC, Baka-D approved these changes

2018-12-03 19:39 UTC, merged