zh / Game_Modes: new translation of GM/osu!catch and little modification of GM/osu!
osu-translate-zh/osu-wiki pull request #87
Opened 2019-08-02 15:29 UTC by Drickle

Worked for 2 days, ~~that's toooooo long bro~~

Some nouns are not determined (such as `catcher`).
Ready for review.

2019-08-02 18:16 UTC, Drickle reviewed
Hotfix

2019-08-02 18:16 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +但是接果人不能从屏幕右侧穿越到屏幕左侧。
```suggestion
但是接果人不能从屏幕一侧穿越到屏幕另一侧。
```

2019-08-02 18:16 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +_[转到 设置 - 输入选项 中的 键盘设置，点击尽管更改按键绑定” 按钮来更改相应的按键。][Options#Keyboard wikilink]_
```suggestion
_[转到 设置 - 输入选项 中的 键盘设置，点击 “更改按键绑定” 按钮来更改相应的按键。][Options#Keyboard wikilink]_
```

2019-08-02 18:16 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +**注意：** osu!standard 和 osu!catch 的分数计算方法有一些差别：There is a difference between osu!standard and osu!catch's scoring methods:-
```suggestion
**注意：** osu!standard 和 osu!catch 的分数计算方法有一些差别：
```

2019-08-04 09:40 UTC, Drickle commented
be516c3: Probably it's my mouse' fault
Middle buttom pastes what you chave chosen, then this thing happened when I scroll around

2019-08-05 13:59 UTC, Zhai2333 commented on wiki/Game_Modes/osu!/zh.md
> +- 涂鸦的存在时间比默认皮肤光标轨迹的要长。
LGTM.

另：用词统一在哪里？

2019-08-05 14:02 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +如果 Miss 了水果液滴就会重置连击数（因为它相当于滑条白点），而水滴就不会。
这里使用 Miss 还是 未接中 比较好？

2019-08-05 14:03 UTC, Drickle commented on wiki/Game_Modes/osu!/zh.md
> +- 涂鸦的存在时间比默认皮肤光标轨迹的要长。
🤔❓

2019-08-05 14:04 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +如果 Miss 了水果液滴就会重置连击数（因为它相当于滑条白点），而水滴就不会。
我个人偏向 Miss

2019-08-05 14:04 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +[ouendan wikipedia]: https://en.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan "维基百科中的「押忍！战斗！应援团」页面"
是否替换为 zh.wikipedia.org ？

2019-08-05 14:04 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +[ouendan wikipedia]: https://en.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan "维基百科中的「押忍！战斗！应援团」页面"
```suggestion
[ouendan wikipedia]: https://zh.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan "维基百科中的「押忍！战斗！应援团」页面"
```

2019-08-05 14:05 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +如果 Miss 了水果液滴（Juice Drops）就会重置连击数（因为它相当于滑条白点），而水滴（Droplets）就不会。
Miss / 未接中

2019-08-05 14:19 UTC, mochaaP requested changes
- 用词统一
- 对于盘古之白格式，尝试 [vinta/pangu](https://github.com/vinta/pangu) 或 [vinta/pangu.js](https://github.com/vinta/pangu.js) ，主流编辑器也有相关插件。
- 中西文符号

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +它并不会减少血条，因此你可以忽略这场~~可以白嫖的~~香蕉雨。
符号错误？
西文而不是中文
```suggestion
它并不会减少血条，因此你可以忽略这场~~可以白嫖的~~香蕉雨。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +**[参考《玩法风格》文章的 osu!catch 一节。][Play_Styles#osu!catch wikilink]**
《》/「」

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +_[转到 设置 - 输入选项 中的 键盘设置，点击 “更改按键绑定” 按钮来更改相应的按键。][Options#Keyboard wikilink]_
`&gt;` 为 > 的 HTML 实体。
同样的，「」/“”？
```suggestion
_[转到 设置 -&gt; 输入选项 中的 键盘设置，点击 “更改按键绑定” 按钮来更改相应的按键。][Options#Keyboard wikilink]_
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +S  | 98.01% 到 99.99% 准确度（像 _osu!mania_ 一样，即使有几个 Miss 还是可以达到 S 等级）
保留句号，并保持中文文法
```suggestion
 S  | 98.01% 到 99.99% 准确度（像 _osu!mania_ 一样，即使有几个 Miss 还是可以达到 S 等级。）
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +### 准确度判定
行号不匹配

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +准确度由接到的水果的多少决定。香蕉雨不会影响准确度。
这个空格是？

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +还有一点，如果使用 osu!API 计算准确度，水滴（ Droplets ）的判定计数会被计算在 **`count50`** 一项中；Miss 的水滴数会被计在 **`countkatu`** 一项。
括号内无需空格
```suggestion
还有一点，如果使用 osu!API 计算准确度，水滴（Droplets）的判定计数会被计算在 **`count50`** 一项中；Miss 的水滴数会被计在 **`countkatu`** 一项。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 水果液滴（ Juice drops，滑条白点）计 100 分，不使用分数倍化器计算。
同样的，此处也不需要。
```suggestion
- 水果液滴（Juice drops，滑条白点）计 100 分，不使用分数倍化器计算。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 最小的液滴（ Droplet，滑条路径 ）计 10 分，不使用分数倍化器计算。
```suggestion
- 最小的液滴（Droplet，滑条路径）计 10 分，不使用分数倍化器计算。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +osu!catch 中，连击不会因为 Miss 了水滴（ Droplets，在谱面分数排行榜被计为 _Miss Droplet_ ）而被打断，但通过接住水滴可以获得更高的精确度和分数。
```suggestion
osu!catch 中，连击不会因为 Miss 了水滴（Droplets，在谱面分数排行榜被计为 _Miss Droplet_）而被打断，但通过接住水滴可以获得更高的精确度和分数。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 收集到果汁液滴（ Juice drops ）。
```suggestion
-  收集到果汁液滴（Juice drops）。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- Miss 了任何一个果汁液滴（ Juice Drops ）。
```suggestion
- Miss 了任何一个果汁液滴（Juice Drops）。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 收集到小水滴（ Droplets ）。
```suggestion
-  收集到小水滴（Droplets）。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 收集到任何水果、果汁液滴（ Juice Drops ）、香蕉。
```suggestion
-  收集到任何水果、果汁液滴（Juice Drops）、香蕉。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 不收集任何水果和果汁液滴（ Juice Drops ）。
```suggestion
-  不收集任何水果和果汁液滴（Juice Drops）。
```

2019-08-05 14:19 UTC, Zhai2333 commented on wiki/Game_Modes/osu!catch/zh.md
> +- 如果使用了 [Auto][Auto wikilink] Mod，玩家的名字就会变成 _salad!_（~~水果~~沙拉）。
```suggestion
-  如果使用了 [Auto][Auto wikilink] Mod，玩家的名字就会变成 _salad!_（~~水果~~沙拉）。
```

2019-08-05 14:20 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +_[转到 设置 - 输入选项 中的 键盘设置，点击 “更改按键绑定” 按钮来更改相应的按键。][Options#Keyboard wikilink]_
No need

2019-08-05 14:21 UTC, Drickle commented on wiki/Game_Modes/osu!catch/zh.md
> +它并不会减少血条，因此你可以忽略这场~~可以白嫖的~~香蕉雨。
删除线啊...

2019-08-09 15:55 UTC, merged